export const TRACKED_NOVEL_PREFIX = 'TRACKED_NOVEL_PREFIX';

export const NOVEL_PAGE_INDEX_PREFIX = 'NOVEL_PAGE_INDEX_PREFIX';

export const LAST_READ_PREFIX = 'LAST_READ_PREFIX';

export const NOVEL_SETTINSG_PREFIX = 'NOVEL_SETTINGS';
