pull_request_title: 'chore: Update Translations'
commit_message: '[ci skip]'
files:
  - source: /strings/languages/en/strings.json
    translation: /strings/languages/%locale_with_underscore%/strings.json
