export const SWITCH_THEME = "SWITCH_THEME";

export const GET_LIBRARY_NOVELS = "GET_LIBRARY_NOVELS";

export const SET_DISPLAY_MODE = "SET_DISPLAY_MODE";

export const SET_ITEMS_PER_ROW = "SET_ITEMS_PER_ROW";

export const GET_EXTENSIONS = "GET_EXTENSIONS";

export const LOADING_NOVEL = "LOADING_NOVEL";

export const LOADING_CHAPTERS = "LOADING_CHAPTERS";

export const GET_NOVEL = "GET_NOVEL";

export const GET_CHAPTERS = "GET_CHAPTERS";

export const CHAPTER_DOWNLOADED = "CHAPTER_DOWNLOADED";

export const CHAPTER_DELETED = "CHAPTER_DELETED";

export const CHAPTER_DOWNLOADING = "CHAPTER_DOWNLOADING";
