export const SWITCH_THEME = "SWITCH_THEME";

export const GET_LIBRARY_NOVELS = "GET_LIBRARY_NOVELS";

export const SET_DISPLAY_MODE = "SET_DISPLAY_MODE";

export const SET_ITEMS_PER_ROW = "SET_ITEMS_PER_ROW";

export const GET_EXTENSIONS = "GET_EXTENSIONS";

export const LOADING_NOVEL = "LOADING_NOVEL";

export const FETCHING_NOVEL = "FETCHING_NOVEL";

export const LOADING_CHAPTERS = "LOADING_CHAPTERS";

export const SET_NOVEL = "SET_NOVEL";

export const GET_NOVEL = "GET_NOVEL";

export const UPDATE_IN_LIBRARY = "UPDATE_IN_LIBRARY";

export const GET_CHAPTERS = "GET_CHAPTERS";

export const CHAPTER_DOWNLOADED = "CHAPTER_DOWNLOADED";

export const CHAPTER_DELETED = "CHAPTER_DELETED";

export const CHAPTER_DOWNLOADING = "CHAPTER_DOWNLOADING";

export const LOAD_HISTORY = "LOAD_HISTORY";

export const UPDATE_NOVEL_HISTORY = "UPDATE_NOVEL_HISTORY";

export const CLEAR_NOVEL_HISTORY = "CLEAR_NOVEL_HISTORY";

export const GET_HISTORY = "GET_HISTORY";

export const CHAPTER_READ = "CHAPTER_READ";

export const GET_CHAPTER = "GET_CHAPTER";

export const CHAPTER_LOADING = "CHAPTER_LOADING";
