export const BACKGROUND_ACTION = 'BACKGROUND_ACTION';

export enum BackgoundAction {
  DOWNLOAD_CHAPTER = 'DOWNLOAD_CHAPTER',
  BACKUP = 'BACKUP',
  RESTORE = 'RESTORE',
  MIGRATE = 'MIGRATE',
  IMPORT_EPUB = 'IMPORT_EPUB',
  UPDATE_LIBRARY = 'UPDATELIBRARY',
}
