export const strawberryDaiquiriTheme = {
  light: {
    id: 16,
    name: 'Strawberry Daiquiri',
    isDark: false,
    primary: '#B61E40',
    onPrimary: '#FFFFFF',
    primaryContainer: '#FFDADD',
    onPrimaryContainer: '#40000D',
    secondary: '#B61E40',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#FFDADD',
    onSecondaryContainer: '#40000D',
    tertiary: '#775930',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#FFDDB1',
    onTertiaryContainer: '#2A1800',
    background: '#FCFCFC',
    onBackground: '#201A1A',
    surface: '#FCFCFC',
    onSurface: '#201A1A',
    surfaceVariant: '#F4DDDD',
    onSurfaceVariant: '#534344',
    outline: '#857374',
    inverseOnSurface: '#FBEDED',
    inverseSurface: '#362F2F',
    primaryInverse: '#FFB2B9',
    elevationOverlay: '#BFDFDF',
    textColorPrimary: '#000000',
    textColorSecondary: 'rgba(0,0,0,0.54)',
    textColorHint: 'rgba(0,0,0,0.38)',
  },
  dark: {
    id: 17,
    name: 'Strawberry Daiquiri',
    isDark: true,
    primary: '#FFB2B9',
    onPrimary: '#67001B',
    primaryContainer: '#91002A',
    onPrimaryContainer: '#FFDADD',
    secondary: '#FFB2B9',
    onSecondary: '#67001B',
    secondaryContainer: '#91002A',
    onSecondaryContainer: '#FFDADD',
    tertiary: '#E8C08E',
    onTertiary: '#432C06',
    tertiaryContainer: '#5D421B',
    onTertiaryContainer: '#FFDDB1',
    background: '#201A1A',
    onBackground: '#ECDFDF',
    surface: '#201A1A',
    onSurface: '#ECDFDF',
    surfaceVariant: '#534344',
    onSurfaceVariant: '#D7C1C2',
    outline: '#A08C8D',
    inverseOnSurface: '#201A1A',
    inverseSurface: '#ECDFDF',
    primaryInverse: '#B61E40',
    elevationOverlay: '#18544E',
    textColorPrimary: '#FFFFFF',
    textColorSecondary: 'rgba(255,255,255,0.7)',
    textColorHint: 'rgba(255,255,255,0.5)',
  },
};
