export const SET_DOWNLOAD_QUEUE = 'SET_DOWNLOAD_QUEUE';
export const CANCEL_DOWNLOAD = 'CANCEL_DOWNLOAD';
export const PAUSE_DOWNLOADS = 'PAUSE_DOWNLOADS';
export const RESUME_DOWNLOADS = 'RESUME_DOWNLOADS';
export const RESTORE_DOWNLOADS_STATE = 'RESTORE_DOWNLOADS_STATE';
