export const GET_UPDATES = 'GET_UPDATES';
export const LOAD_UPDATES = 'LOAD_UPDATES';
export const SET_LAST_UPDATE_TIME = 'SET_LAST_UPDATE_TIME';
export const SHOW_LAST_UPDATE_TIME = 'SHOW_LAST_UPDATE_TIME';
export const RESTORE_UPDATE_STATE = 'RESTORE_UPDATE_STATE';
