import MultiSrcScraper from './ReadwnScraper';

const ReadwnScraper = new MultiSrcScraper(
  68,
  'https://www.wuxiap.com/',
  'Readwn.com',
  {
    label: 'Genre / Category',
    values: [
      { label: 'All', value: 'all' },
      { label: 'Action', value: 'action' },
      { label: 'Adventure', value: 'adventure' },
      { label: 'Chinese', value: 'chinese' },
      { label: 'Comedy', value: 'comedy' },
      { label: 'Contemporary Romance', value: 'contemporary-romance' },
      { label: 'Drama', value: 'drama' },
      { label: 'Eastern Fantasy', value: 'eastern-fantasy' },
      { label: 'Ecchi', value: 'ecchi' },
      { label: 'Erciyuan', value: 'erciyuan' },
      { label: 'Faloo', value: 'faloo' },
      { label: 'Fan-Fiction', value: 'fan-fiction' },
      { label: 'Fantasy', value: 'fantasy' },
      { label: 'Fantasy Romance', value: 'fantasy-romance' },
      { label: 'Game', value: 'game' },
      { label: 'Gender Bender', value: 'gender-bender' },
      { label: 'Harem', value: 'harem' },
      { label: 'Hentai', value: 'hentai' },
      { label: 'Historical', value: 'historical' },
      { label: 'Horror', value: 'horror' },
      { label: 'Isekai', value: 'isekai' },
      { label: 'Japanese', value: 'japanese' },
      { label: 'Josei', value: 'josei' },
      { label: 'Korean', value: 'korean' },
      { label: 'Lolicon', value: 'lolicon' },
      { label: 'Magic', value: 'magic' },
      { label: 'Magical Realism', value: 'magical-realism' },
      { label: 'Martial Arts', value: 'martial-arts' },
      { label: 'Mecha', value: 'mecha' },
      { label: 'Military', value: 'military' },
      { label: 'Mystery', value: 'mystery' },
      { label: 'Official Circles', value: 'official_circles' },
      { label: 'Psychological', value: 'psychological' },
      { label: 'Romance', value: 'romance' },
      { label: 'School Life', value: 'school-life' },
      { label: 'Sci-fi', value: 'sci-fi' },
      { label: 'Science Fiction', value: 'science_fiction' },
      { label: 'Seinen', value: 'seinen' },
      { label: 'Shoujo', value: 'shoujo' },
      { label: 'Shoujo Ai', value: 'shoujo-ai' },
      { label: 'Shounen', value: 'shounen' },
      { label: 'Shounen Ai', value: 'shounen-ai' },
      { label: 'Slice of Life', value: 'slice-of-life' },
      { label: 'Sports', value: 'sports' },
      { label: 'Supernatural', value: 'supernatural' },
      { label: 'Suspense Thriller', value: 'suspense_thriller' },
      { label: 'Tragedy', value: 'tragedy' },
      { label: 'Travel Through Time', value: 'travel_through_time' },
      { label: 'Two-dimensional', value: 'two-dimensional' },
      { label: 'Urban', value: 'urban' },
      { label: 'Urban Life', value: 'urban-life' },
      { label: 'Video Games', value: 'video-games' },
      { label: 'Virtual Reality', value: 'virtual-reality' },
      { label: 'Wuxia', value: 'wuxia' },
      { label: 'Wuxia Xianxia', value: 'wuxia_xianxia' },
      { label: 'Xianxia', value: 'xianxia' },
      { label: 'Xuanhuan', value: 'xuanhuan' },
      { label: 'Yaoi', value: 'yaoi' },
      { label: 'Yuri', value: 'yuri' },
    ],
  },
);

const NovelmtScraper = new MultiSrcScraper(
  99,
  'https://www.wuxiapub.com/',
  'Novelmt.com',
  {
    label: 'Genre / Category',
    values: [
      { label: 'All', value: 'all' },
      { label: 'Action', value: 'action' },
      { label: 'Adult', value: 'adult' },
      { label: 'Adventure', value: 'adventure' },
      { label: 'Billionaire', value: 'billionaire' },
      { label: 'CEO', value: 'ceo' },
      { label: 'Chinese', value: 'chinese' },
      { label: 'Comedy', value: 'comedy' },
      { label: 'Contemporary Romance', value: 'contemporary-romance' },
      { label: 'Drama', value: 'drama' },
      { label: 'Eastern Fantasy', value: 'eastern-fantasy' },
      { label: 'Ecchi', value: 'ecchi' },
      { label: 'Erciyuan', value: 'erciyuan' },
      { label: 'Faloo', value: 'faloo' },
      { label: 'Fan-Fiction', value: 'fan-fiction' },
      { label: 'Fantasy', value: 'fantasy' },
      { label: 'Fantasy Romance', value: 'fantasy-romance' },
      { label: 'Farming', value: 'farming' },
      { label: 'Game', value: 'game' },
      { label: 'Games', value: 'games' },
      { label: 'Gay Romance', value: 'gay-romance' },
      { label: 'Gender Bender', value: 'gender-bender' },
      { label: 'Harem', value: 'harem' },
      { label: 'Historical', value: 'historical' },
      { label: 'Historical Romance', value: 'historical-romance' },
      { label: 'Horror', value: 'horror' },
      { label: 'Isekai', value: 'isekai' },
      { label: 'Japanese', value: 'japanese' },
      { label: 'Josei', value: 'josei' },
      { label: 'Korean', value: 'korean' },
      { label: 'Lolicon', value: 'lolicon' },
      { label: 'Magic', value: 'magic' },
      { label: 'Magical Realism', value: 'magical-realism' },
      { label: 'Martial Arts', value: 'martial-arts' },
      { label: 'Mature', value: 'mature' },
      { label: 'Mecha', value: 'mecha' },
      { label: 'Military', value: 'military' },
      { label: 'Modern Life', value: 'modern-life' },
      { label: 'Modern Romance', value: 'modern-romance' },
      { label: 'Mystery', value: 'mystery' },
      { label: 'Psychological', value: 'psychological' },
      { label: 'Romance', value: 'romance' },
      { label: 'Romantic', value: 'romantic' },
      { label: 'School Life', value: 'school-life' },
      { label: 'Sci-fi', value: 'sci-fi' },
      { label: 'Seinen', value: 'seinen' },
      { label: 'Shoujo', value: 'shoujo' },
      { label: 'Shoujo Ai', value: 'shoujo-ai' },
      { label: 'Shounen', value: 'shounen' },
      { label: 'Shounen Ai', value: 'shounen-ai' },
      { label: 'Slice of Life', value: 'slice-of-life' },
      { label: 'Smut', value: 'smut' },
      { label: 'Sports', value: 'sports' },
      { label: 'Supernatural', value: 'supernatural' },
      { label: 'Tragedy', value: 'tragedy' },
      { label: 'Two-dimensional', value: 'two-dimensional' },
      { label: 'Urban', value: 'urban' },
      { label: 'Urban Life', value: 'urban-life' },
      { label: 'Video Games', value: 'video-games' },
      { label: 'Virtual Reality', value: 'virtual-reality' },
      { label: 'Wuxia', value: 'wuxia' },
      { label: 'Xianxia', value: 'xianxia' },
      { label: 'Xuanhuan', value: 'xuanhuan' },
      { label: 'Yaoi', value: 'yaoi' },
      { label: 'Yuri', value: 'yuri' },
    ],
  },
);

const LtnovelScraper = new MultiSrcScraper(
  100,
  'https://www.ltnovel.com/',
  'Ltnovel.com',
  {
    label: 'Genre / Category',
    values: [
      { label: 'All', value: 'all' },
      { label: 'Action', value: 'action' },
      { label: 'Adult', value: 'adult' },
      { label: 'Adventure', value: 'adventure' },
      { label: 'Comedy', value: 'comedy' },
      { label: 'Contemporary Romance', value: 'contemporary-romance' },
      { label: 'Drama', value: 'drama' },
      { label: 'Eastern Fantasy', value: 'eastern-fantasy' },
      { label: 'Ecchi', value: 'ecchi' },
      { label: 'Fantasy', value: 'fantasy' },
      { label: 'Fantasy Romance', value: 'fantasy-romance' },
      { label: 'Game', value: 'game' },
      { label: 'Gender Bender', value: 'gender-bender' },
      { label: 'Harem', value: 'harem' },
      { label: 'Historical', value: 'historical' },
      { label: 'Horror', value: 'horror' },
      { label: 'Josei', value: 'josei' },
      { label: 'Lolicon', value: 'lolicon' },
      { label: 'Magical Realism', value: 'magical-realism' },
      { label: 'Martial Arts', value: 'martial-arts' },
      { label: 'Mature', value: 'mature' },
      { label: 'Mecha', value: 'mecha' },
      { label: 'Mystery', value: 'mystery' },
      { label: 'Psychological', value: 'psychological' },
      { label: 'Romance', value: 'romance' },
      { label: 'School Life', value: 'school-life' },
      { label: 'Sci-fi', value: 'sci-fi' },
      { label: 'Seinen', value: 'seinen' },
      { label: 'Shoujo', value: 'shoujo' },
      { label: 'Shounen', value: 'shounen' },
      { label: 'Shounen Ai', value: 'shounen-ai' },
      { label: 'Slice of Life', value: 'slice-of-life' },
      { label: 'Smut', value: 'smut' },
      { label: 'Sports', value: 'sports' },
      { label: 'Supernatural', value: 'supernatural' },
      { label: 'Tragedy', value: 'tragedy' },
      { label: 'Video Games', value: 'video-games' },
      { label: 'Wuxia', value: 'wuxia' },
      { label: 'Xianxia', value: 'xianxia' },
      { label: 'Xuanhuan', value: 'xuanhuan' },
      { label: 'Yaoi', value: 'yaoi' },
    ],
  },
);

export { ReadwnScraper, NovelmtScraper, LtnovelScraper };
