export const GET_SOURCES = 'GET_SOURCES';
export const SEARCH_SOURCES = 'SEARCH_SOURCES';
export const PIN_SOURCES = 'PIN_SOURCES';
export const FILTER_LANGUAGE = 'FILTER_LANGUAGE';
export const ENABLE_DISCOVER = 'ENABLE_DISCOVER';
