export const SET_CHAPTER_LIST_PREF = 'SET_CHAPTER_LIST_PREF';
export const SET_LAST_READ = 'SET_LAST_READ';
export const SAVE_SCROLL_POSITION = 'SAVE_SCROLL_POSITION';
export const RESTORE_PREFERENCE_STATE = 'RESTORE_PREFERENCE_STATE';
