import { FilterInputs } from '../types/filterTypes';
import { htmlToText } from '../helpers/htmlToText';
import { Status } from '../helpers/constants';
import * as cheerio from 'cheerio';
import { defaultTo } from 'lodash-es';

const sourceId = 118;
const sourceName = 'Rulate';

const baseUrl = 'https://tl.rulate.ru';

const popularNovels = async (page, { showLatestNovels, filters }) => {
  let url = baseUrl + '/search?t=&cat=2';
  url += '&sort=' + defaultTo(filters?.sort, showLatestNovels ? '4' : '6');
  url += '&type=' + defaultTo(filters?.type, '0');
  url += '&atmosphere=' + defaultTo(filters?.atmosphere, '0');
  url += '&adult=' + defaultTo(filters?.adult, '0');

  if (filters?.genres?.length) {
    url += filters.genres.map(i => `&genres[]=${i}`).join('');
  }

  if (filters?.tags?.length) {
    url += filters.tags.map(i => `&tags[]=${i}`).join('');
  }

  if (filters?.trash?.length) {
    url += filters.trash.map(i => `&${i}=1`);
  }

  url += `&Book_page=${page}`;

  const result = await fetch(url);
  const body = await result.text();
  const loadedCheerio = cheerio.load(body);

  let totalPages =
    loadedCheerio('div[class="pagination"] > ul > li:last-child > a')
      .attr('href')
      ?.split('/Book_page/')[1] || '0';

  totalPages = parseInt(totalPages, 10);
  let novels = [];

  loadedCheerio(
    'ul[class="search-results"] > li:not([class="ad_type_catalog"])',
  ).each(function () {
    const novelName = loadedCheerio(this).find('p > a').text();
    const novelCover = baseUrl + loadedCheerio(this).find('img').attr('src');
    const novelUrl = loadedCheerio(this).find('p > a').attr('href');

    const novel = { sourceId, novelName, novelCover, novelUrl };
    novels.push(novel);
  });

  return { totalPages, novels };
};

const parseNovelAndChapters = async novelUrl => {
  let result = await fetch(baseUrl + novelUrl);
  if (result.url.includes('mature?path=')) {
    const formData = new FormData();
    formData.append('path', novelUrl);
    formData.append('ok', 'Да');

    await fetch(result.url, {
      method: 'POST',
      body: formData,
    });

    result = await fetch(baseUrl + novelUrl);
  }
  const body = await result.text();
  const loadedCheerio = cheerio.load(body);

  let novel = {
    sourceId,
    sourceName,
    url: baseUrl + novelUrl,
    novelUrl,
  };

  novel.novelName = loadedCheerio('div[class="container"] > div > div > h1')
    .text()
    .trim();
  novel.novelCover =
    baseUrl + loadedCheerio('div[class="images"] > div img').attr('src');
  novel.summary = loadedCheerio('#Info > div:nth-child(3)').html();
  novel.genre = [];

  if (novel?.summary) {
    novel.summary = htmlToText(novel.summary);
  }

  let chapters = [];
  loadedCheerio('div[class="span5"] > p').each(function () {
    switch (loadedCheerio(this).find('strong').text()) {
      case 'Автор:':
        novel.author = loadedCheerio(this).find('em > a').text().trim();
        break;
      case 'Выпуск:':
        novel.status =
          loadedCheerio(this).find('em').text().trim() === 'продолжается'
            ? Status.ONGOING
            : Status.COMPLETED;
        break;
      case 'Тэги:':
        loadedCheerio(this)
          .find('em > a')
          .each(function () {
            novel.genre.push(loadedCheerio(this).text());
          });
        break;
      case 'Жанры:':
        loadedCheerio(this)
          .find('em > a')
          .each(function () {
            novel.genre.push(loadedCheerio(this).text());
          });
        break;
    }
  });

  if (novel.genre.length > 0) {
    novel.genre = novel.genre.reverse().join(',');
  } else {
    novel.genre = '';
  }

  loadedCheerio('table > tbody > tr.chapter_row').each(function () {
    const chapterName = loadedCheerio(this)
      .find('td[class="t"] > a')
      .text()
      .trim();
    const releaseDate = loadedCheerio(this)
      .find('td > span')
      .attr('title')
      ?.trim();
    const chapterUrl = loadedCheerio(this)
      .find('td[class="t"] > a')
      .attr('href');

    if (
      loadedCheerio(this).find('td > span[class="disabled"]').length < 1 &&
      releaseDate
    ) {
      chapters.push({ chapterName, releaseDate, chapterUrl });
    }
  });

  novel.chapters = chapters;
  return novel;
};

const parseChapter = async (novelUrl, chapterUrl) => {
  let result = await fetch(baseUrl + chapterUrl);
  if (result.url.includes('mature?path=')) {
    const formData = new FormData();
    formData.append('path', novelUrl);
    formData.append('ok', 'Да');

    await fetch(result.url, {
      method: 'POST',
      body: formData,
    });

    result = await fetch(baseUrl + chapterUrl);
  }
  const body = await result.text();
  const loadedCheerio = cheerio.load(body);

  loadedCheerio('.content-text img').each(function () {
    if (!loadedCheerio(this).attr('src')?.startsWith('http')) {
      const src = loadedCheerio(this).attr('src');
      loadedCheerio(this).attr('src', baseUrl + src);
    }
  });

  const chapterName = loadedCheerio(
    '.chapter_select > select > option[selected]',
  )
    .text()
    .trim();
  const chapterText = loadedCheerio('.content-text').html();

  const chapter = {
    sourceId,
    novelUrl,
    chapterUrl,
    chapterName,
    chapterText,
  };

  return chapter;
};

const searchNovels = async searchTerm => {
  const result = await fetch(
    baseUrl + '/search/autocomplete?query=' + searchTerm,
  );
  let json = await result.json();
  let novels = [];

  json.map(item => {
    const novelName = item.title_one + ' / ' + item.title_two;
    const novelCover = baseUrl + item.img;
    const novelUrl = item.url;

    novels.push({ sourceId, novelName, novelCover, novelUrl });
  });

  return novels;
};

const filters = [
  {
    key: 'sort',
    label: 'Сортировка',
    values: [
      { label: 'По рейтингу', value: '6' },
      { label: 'По степени готовности', value: '0' },
      { label: 'По названию на языке оригинала', value: '1' },
      { label: 'По названию на языке перевода', value: '2' },
      { label: 'По дате создания', value: '3' },
      { label: 'По дате последней активности', value: '4' },
      { label: 'По просмотрам', value: '5' },
      { label: 'По кол-ву переведённых глав', value: '7' },
      { label: 'По кол-ву лайков', value: '8' },
      { label: 'По кол-ву страниц', value: '10' },
      { label: 'По кол-ву бесплатных глав', value: '11' },
      { label: 'По кол-ву рецензий', value: '12' },
      { label: 'По кол-ву в закладках', value: '13' },
      { label: 'По кол-ву в избранном', value: '14' },
    ],
    inputType: FilterInputs.Picker,
  },
  {
    key: 'type',
    label: 'Тип',
    values: [
      { label: 'Неважно', value: '0' },
      { label: 'Только переводы', value: '1' },
      { label: 'Только авторские', value: '2' },
    ],
    inputType: FilterInputs.Picker,
  },

  {
    key: 'atmosphere',
    label: 'Атмосфера',
    values: [
      { label: 'Неважно', value: '0' },
      { label: 'Позитивная', value: '1' },
      { label: 'Dark', value: '2' },
    ],
    inputType: FilterInputs.Picker,
  },
  {
    key: 'trash',
    label: 'Другое',
    values: [
      { label: 'Готовые на 100%', value: 'ready' },
      { label: 'Доступные для перевода', value: 'tr' },
      { label: 'Доступные для скачивания', value: 'gen' },
      { label: 'Завершённые проекты', value: 'wealth' },
      { label: 'Распродажа', value: 'discount' },
      { label: 'Только онгоинги', value: 'ongoings' },
      { label: 'Убрать машинный', value: 'remove_machinelate' },
    ],
    inputType: FilterInputs.Checkbox,
  },
  {
    key: 'genres',
    label: 'Жанры',
    values: [
      { label: 'Арт', value: '1' },
      { label: 'Боевик', value: '2' },
      { label: 'Боевые искусства', value: '3' },
      { label: 'Вампиры', value: '4' },
      { label: 'Гарем', value: '5' },
      { label: 'Героическое фэнтези', value: '7' },
      { label: 'Детектив', value: '8' },
      { label: 'Дзёсэй', value: '9' },
      { label: 'Додзинси', value: '10' },
      { label: 'Драма', value: '11' },
      { label: 'Игра', value: '12' },
      { label: 'История', value: '13' },
      { label: 'Киберпанк', value: '46' },
      { label: 'Кодомо', value: '14' },
      { label: 'Комедия', value: '15' },
      { label: 'Литрпг', value: '48' },
      { label: 'Махо-сёдзё', value: '16' },
      { label: 'Мелодрама', value: '49' },
      { label: 'Меха', value: '17' },
      { label: 'Мистика', value: '18' },
      { label: 'Научная фантастика', value: '19' },
      { label: 'Повседневность', value: '20' },
      { label: 'Постапокалиптика', value: '21' },
      { label: 'Приключения', value: '22' },
      { label: 'Психология', value: '23' },
      { label: 'Романтика', value: '24' },
      { label: 'Самурайский боевик', value: '25' },
      { label: 'Сверхъестественное', value: '26' },
      { label: 'Сёдзё', value: '27' },
      { label: 'Сёнэн', value: '29' },
      { label: 'Смат', value: '45' },
      { label: 'Спорт', value: '31' },
      { label: 'Сэйнэн', value: '32' },
      { label: 'Сюаньхуа', value: '44' },
      { label: 'Сюаньхуань', value: '47' },
      { label: 'Сянься (XianXia)', value: '42' },
      { label: 'Трагедия', value: '33' },
      { label: 'Триллер', value: '34' },
      { label: 'Ужасы', value: '35' },
      { label: 'Уся (wuxia)', value: '41' },
      { label: 'Фантастика', value: '36' },
      { label: 'Фанфик', value: '50' },
      { label: 'Фэнтези', value: '37' },
      { label: 'Школа', value: '38' },
      { label: 'Этти', value: '39' },
      { label: 'Bl/Яой', value: '43' },
      { label: 'Gl/Юри', value: '40' },
    ],
    inputType: FilterInputs.Checkbox,
  },
  {
    key: 'tags',
    label: 'Тэги',
    values: [
      { label: 'Абсурд', value: '7973' },
      { label: 'Авантюристы', value: '222' },
      { label: 'Автомат', value: '5272' },
      { label: 'Авторский мир', value: '1062' },
      { label: 'Агрессивные персонажи', value: '3249' },
      { label: 'Ад', value: '2623' },
      { label: 'Ад и рай', value: '817' },
      { label: 'Адам дженсен', value: '1649' },
      { label: 'Адаптация произведения', value: '192' },
      { label: 'Адвокат', value: '6340' },
      { label: 'Адекватные главные герои', value: '1953' },
      { label: 'Азартные игры', value: '5301' },
      { label: 'Азгард', value: '3494' },
      { label: 'Азула', value: '5550' },
      { label: 'Аид', value: '7641' },
      { label: 'Айдолы', value: '4081' },
      { label: 'Академия', value: '316' },
      { label: 'Акамэ', value: '5059' },
      { label: 'Аквакинез', value: '5952' },
      { label: 'Акира', value: '2639' },
      { label: 'Акнология', value: '4634' },
      { label: 'Актерское мастерство', value: '4798' },
      { label: 'Актёры', value: '7506' },
      { label: 'Активные герои', value: '6376' },
      { label: 'Акутагава рюноске', value: '4113' },
      { label: 'Аладдин', value: '6489' },
      { label: 'Алая ведьма', value: '4767' },
      { label: 'Алиса', value: '4761' },
      { label: 'Алкоголь', value: '5508' },
      { label: 'Аллегория', value: '271' },
      { label: 'Алукард', value: '4914' },
      { label: 'Алхимики', value: '1164' },
      { label: 'Алхимия', value: '1473' },
      { label: 'Алчность', value: '6897' },
      { label: 'Альбус дамблдор', value: '5784' },
      { label: 'Альтернативное развитие событий', value: '5330' },
      { label: 'Альянсы', value: '328' },
      { label: 'Амбициозный главный герой', value: '3751' },
      { label: 'Америка', value: '4082' },
      { label: 'Амнезия', value: '2207' },
      { label: 'Аморальный герой', value: '18' },
      { label: 'Анальный секс', value: '1942' },
      { label: 'Анбу', value: '8129' },
      { label: 'Ангелы', value: '857' },
      { label: 'Ангелы и демоны', value: '1327' },
      { label: 'Ангст', value: '4638' },
      { label: 'Андроиды', value: '1993' },
      { label: 'Анимализм', value: '5249' },
      { label: 'Аниме', value: '1294' },
      { label: 'Анко митараши', value: '5768' },
      { label: 'Антагонист', value: '2144' },
      { label: 'Антигерой', value: '7725' },
      { label: 'Антиквариат', value: '3552' },
      { label: 'Антимаг', value: '1348' },
      { label: 'Антиутопия', value: '662' },
      { label: 'Апокалипсис', value: '1498' },
      { label: 'Аристократия', value: '371' },
      { label: 'Аристократы', value: '7338' },
      { label: 'Армия', value: '1723' },
      { label: 'Артас', value: '6700' },
      { label: 'Артефакты', value: '2296' },
      { label: 'Археология', value: '6523' },
      { label: 'Асгард', value: '3635' },
      { label: 'Ассасин', value: '1415' },
      { label: 'Асуна', value: '5044' },
      { label: 'Аугментации', value: '7751' },
      { label: 'Ацуши накаджима', value: '4109' },
      { label: 'Аянокоджи киетака', value: '6862' },
      { label: 'Бандиты', value: '2188' },
      { label: 'Басейн', value: '6847' },
      { label: 'Баскетбол', value: '7933' },
      { label: 'Бастарды', value: '76' },
      { label: 'Бдсм', value: '444' },
      { label: 'Бедность', value: '1207' },
      { label: 'Без культивации', value: '668' },
      { label: 'Без любовной линий', value: '2225' },
      { label: 'Без перерождений', value: '262' },
      { label: 'Без попаданца', value: '8065' },
      { label: 'Без системы', value: '747' },
      { label: 'Без цензуры', value: '7525' },
      { label: 'Без юмора', value: '763' },
      { label: 'Бездна', value: '1026' },
      { label: 'Безжалостное домашнее животное', value: '1245' },
      { label: 'Безжалостные персонажи', value: '2986' },
      { label: 'Беззаботные персонажи ', value: '3123' },
      { label: 'Безответная любовь', value: '7815' },
      { label: 'Безработный', value: '2202' },
      { label: 'Безумие', value: '37' },
      { label: 'Безумные персонажи', value: '2049' },
      { label: 'Бейсбол', value: '7623' },
      { label: 'Беременность', value: '2122' },
      { label: 'Бесконечный поток', value: '7556' },
      { label: 'Беспечные персонажи', value: '742' },
      { label: 'Бессмертные персонажи', value: '566' },
      { label: 'Бесстрашные персонажи', value: '6921' },
      { label: 'Бесстыдные персонажи', value: '1257' },
      { label: 'Бесстыдный главный герой', value: '8190' },
      { label: 'Библиотека', value: '4210' },
      { label: 'Библия', value: '488' },
      { label: 'Бизнес', value: '704' },
      { label: 'Биология', value: '2220' },
      { label: 'Биомехи', value: '1968' },
      { label: 'Биседзе', value: '777' },
      { label: 'Битва за веру', value: '721' },
      { label: 'Битва за трон', value: '7211' },
      { label: 'Битва королевств', value: '1151' },
      { label: 'Битва рас', value: '6989' },
      { label: 'Битвы', value: '1740' },
      { label: 'Благородные персонажи', value: '2201' },
      { label: 'Близнецы', value: '2931' },
      { label: 'Богатство', value: '6522' },
      { label: 'Богатые персонажи', value: '520' },
      { label: 'Боги', value: '173' },
      { label: 'Богини', value: '30' },
      { label: 'Богиня', value: '8324' },
      { label: 'Богоубийца', value: '1253' },
      { label: 'Богохульство', value: '95' },
      { label: 'Боевая академия', value: '2108' },
      { label: 'Боевик', value: '529' },
      { label: 'Боевые искусства', value: '2090' },
      { label: 'Большая грудь', value: '4717' },
      { label: 'Большой член', value: '5299' },
      { label: 'Бондаж', value: '8319' },
      { label: 'Борос', value: '6533' },
      { label: 'Борьба', value: '1925' },
      { label: 'Борьба за власть', value: '8072' },
      { label: 'Босс и подчиненный', value: '7157' },
      { label: 'Бояръ', value: '2307' },
      { label: 'Брак', value: '1558' },
      { label: 'Брак по договоренности', value: '8310' },
      { label: 'Брак по расчету', value: '1389' },
      { label: 'Брат и сестра', value: '615' },
      { label: 'Братский комплекс', value: '2321' },
      { label: 'Броманс', value: '1103' },
      { label: 'Брошенные дети', value: '2846' },
      { label: 'Буддизм', value: '1871' },
      { label: 'Будущее', value: '1820' },
      { label: 'Бывший муж', value: '8080' },
      { label: 'Быстрое развитие', value: '1443' },
      { label: 'Бэтгерл', value: '2584' },
      { label: 'Бэтмен', value: '4668' },
      { label: 'В первый раз', value: '6212' },
      { label: 'В этот же мир', value: '49' },
      { label: 'Вагинальный секс', value: '4742' },
      { label: 'Ваканда', value: '8331' },
      { label: 'Валькирии', value: '4047' },
      { label: 'Вампиры', value: '2206' },
      { label: 'Веб камера', value: '5664' },
      { label: 'Веб новелла', value: '2349' },
      { label: 'Ведьмак', value: '843' },
      { label: 'Ведьмы', value: '643' },
      { label: 'Везучие персонажи', value: '1879' },
      { label: 'Великолепный лжец', value: '8327' },
      { label: 'Веном', value: '3994' },
      { label: 'Вестерн', value: '2131' },
      { label: 'Вестерос', value: '8171' },
      { label: 'Взросление', value: '624' },
      { label: 'Взрослый главный герой', value: '2416' },
      { label: 'Видео игры', value: '2630' },
      { label: 'Викинги', value: '267' },
      { label: 'Вино', value: '6972' },
      { label: 'Вирт', value: '6213' },
      { label: 'Виртуальная реальность', value: '325' },
      { label: 'Вирусы', value: '3327' },
      { label: 'Владыка демонов', value: '555' },
      { label: 'Властная пара', value: '8332' },
      { label: 'властная пара', value: '8323' },
      { label: 'Власть', value: '756' },
      { label: 'Влюбленность', value: '6132' },
      { label: 'Внешний вид отличается от личности', value: '1938' },
      { label: 'Военные', value: '1096' },
      { label: 'Возрождение', value: '1160' },
      { label: 'Воины', value: '287' },
      { label: 'Война', value: '443' },
      { label: 'Войны', value: '2431' },
      { label: 'Воландеморт', value: '4278' },
      { label: 'Волейбол', value: '6415' },
      { label: 'Волки', value: '1166' },
      { label: 'Волшебники', value: '122' },
      { label: 'Волшебные существа', value: '1689' },
      { label: 'Волшебство', value: '719' },
      { label: 'Вор', value: '1399' },
      { label: 'Воровка', value: '6948' },
      { label: 'Ворон', value: '848' },
      { label: 'Воскрешение', value: '6915' },
      { label: 'Воспоминания из другого мира', value: '1366' },
      { label: 'Воспоминания из прошлого', value: '1372' },
      { label: 'Воссоединие семьи', value: '8130' },
      { label: 'Восхождение', value: '380' },
      { label: 'Враги становятся любовниками', value: '978' },
      { label: 'Врата', value: '40' },
      { label: 'Врата в другой мир', value: '1957' },
      { label: 'Врач', value: '1243' },
      { label: 'Временная петля', value: '2852' },
      { label: 'Врмморпг', value: '2043' },
      { label: 'Все дозволено', value: '96' },
      { label: 'Всемогущий главный герой', value: '1414' },
      { label: 'Второй шанс', value: '2372' },
      { label: 'Вуайеризм', value: '2498' },
      { label: 'Выживание', value: '501' },
      { label: 'Вымышленные существа', value: '3466' },
      { label: 'Вынужденный брак', value: '7705' },
      { label: 'Высокие технологии', value: '653' },
      { label: 'Высокомерные персонажи', value: '3250' },
      { label: 'Галустян', value: '5199' },
      { label: 'Гангстеры', value: '7704' },
      { label: 'Гарем', value: '440' },
      { label: 'Гарри поттер', value: '226' },
      { label: 'Геймеры', value: '2130' },
      { label: 'Генетические модификации', value: '1750' },
      { label: 'Гениальный главный герой', value: '1500' },
      { label: 'Гений', value: '1650' },
      { label: 'Гермиона грейнджер', value: '4280' },
      { label: 'Герои', value: '185' },
      { label: 'Героическое фэнтези', value: '1148' },
      { label: 'Гильгамеш', value: '6031' },
      { label: 'Гильдии', value: '900' },
      { label: 'Гильдия авантюристов', value: '1858' },
      { label: 'Гинтама', value: '4544' },
      { label: 'Гипноз', value: '358' },
      { label: 'Главная героиня влюбляется первой', value: '973' },
      { label: 'Главный герой бог', value: '164' },
      { label: 'Главный герой влюбляется первым', value: '3629' },
      { label: 'Главный герой выживальщик', value: '120' },
      { label: 'Главный герой гонг', value: '7877' },
      { label: 'Главный герой девушка', value: '257' },
      { label: 'Главный герой демон', value: '136' },
      { label: 'Главный герой женщина', value: '7329' },
      { label: 'Главный герой жестокий', value: '1553' },
      { label: 'Главный герой извращенец', value: '94' },
      { label: 'Главный герой имба', value: '2421' },
      { label: 'Главный герой киборг', value: '7780' },
      { label: 'Главный герой монстр', value: '869' },
      { label: 'Главный герой мужчина', value: '1997' },
      { label: 'Главный герой на стороне сил зла', value: '1514' },
      { label: 'Главный герой не адекватный', value: '5' },
      { label: 'Главный герой не психопат', value: '7804' },
      { label: 'Главный герой не человек', value: '2172' },
      { label: 'Главный герой не эмоционален', value: '1150' },
      { label: 'Главный герой подросток', value: '2215' },
      { label: 'Главный герой позитивный', value: '7787' },
      { label: 'Главный герой психопат', value: '7803' },
      { label: 'Главный герой ребенок', value: '2347' },
      { label: 'Главный герой русский', value: '2417' },
      { label: 'Главный герой сильный с самого начала', value: '88' },
      { label: 'Главный герой скрывает свою силу', value: '1059' },
      { label: 'Главный герой эгоист', value: '8326' },
      { label: 'Глотание спермы', value: '4491' },
      { label: 'Гномы', value: '1870' },
      { label: 'Гоблины', value: '2029' },
      { label: 'Годзилла', value: '6990' },
      { label: 'Големы', value: '1690' },
      { label: 'Голливуд', value: '7754' },
      { label: 'Головоломка', value: '1697' },
      { label: 'Горничные', value: '8091' },
      { label: 'Гробница', value: '388' },
      { label: 'Групповой секс', value: '1314' },
      { label: 'Дазай осаму', value: '4112' },
      { label: 'Даньмэй', value: '3411' },
      { label: 'Даосизм', value: '258' },
      { label: 'Дарк соулс', value: '6057' },
      { label: 'Дарт вейдер', value: '6826' },
      { label: 'Дафна гринграсс', value: '5192' },
      { label: 'Дворяне', value: '7204' },
      { label: 'Девушки', value: '7668' },
      { label: 'Девушки монстры', value: '2231' },
      { label: 'Дейви джонс', value: '8061' },
      { label: 'Действие', value: '1425' },
      { label: 'Демон лорд', value: '153' },
      { label: 'Демонология', value: '2024' },
      { label: 'Демоны', value: '1406' },
      { label: 'Депрессия', value: '8313' },
      { label: 'Детектив', value: '1265' },
      { label: 'Дети', value: '580' },
      { label: 'Джарвис', value: '933' },
      { label: 'Джедай', value: '4442' },
      { label: 'Джин', value: '4024' },
      { label: 'Джокер', value: '3351' },
      { label: 'Джон сноу', value: '7412' },
      { label: 'Джоффри баратеон', value: '3936' },
      { label: 'Дзесэй', value: '678' },
      { label: 'Дин винчестер', value: '6953' },
      { label: 'Династии', value: '2982' },
      { label: 'Динозавры', value: '3666' },
      { label: 'Директор', value: '1417' },
      { label: 'Для девушек', value: '1441' },
      { label: 'Дневник', value: '298' },
      { label: 'Добби', value: '6762' },
      { label: 'Добрый мир', value: '1685' },
      { label: 'Договоры с богами', value: '2152' },
      { label: 'Договоры с демонами', value: '1922' },
      { label: 'Доктор', value: '1991' },
      { label: 'Доктор стрэндж', value: '7634' },
      { label: 'Доминирование', value: '2054' },
      { label: 'Дота', value: '6965' },
      { label: 'Доудзюцу', value: '7133' },
      { label: 'Дочь', value: '3291' },
      { label: 'Драко малфой', value: '46' },
      { label: 'Драконы', value: '282' },
      { label: 'Драконы оборотни', value: '8082' },
      { label: 'Драма', value: '611' },
      { label: 'Древние времена', value: '7781' },
      { label: 'Древний египет', value: '7614' },
      { label: 'Древний китай', value: '473' },
      { label: 'Древний мир', value: '4' },
      { label: 'Дрочка', value: '4565' },
      { label: 'Другая вселенная', value: '39' },
      { label: 'Другие планеты', value: '2371' },
      { label: 'Другой мир', value: '2248' },
      { label: 'Дружба', value: '1903' },
      { label: 'Друзья детства', value: '1153' },
      { label: 'Духи', value: '114' },
      { label: 'Духовные силы', value: '1955' },
      { label: 'Души', value: '1212' },
      { label: 'Дьявол', value: '1094' },
      { label: 'Дьявольские фрукты', value: '1564' },
      { label: 'Дэдпул', value: '4399' },
      { label: 'Евнух', value: '6293' },
      { label: 'Европейская атмосфера', value: '5837' },
      { label: 'Египет', value: '528' },
      { label: 'Еда', value: '2056' },
      { label: 'Единороги', value: '437' },
      { label: 'Екаи', value: '655' },
      { label: 'Жалкий главный герой', value: '97' },
      { label: 'Жена', value: '5729' },
      { label: 'Женское доминирование', value: '4622' },
      { label: 'Женщина в теле мужчины', value: '2748' },
      { label: 'Женщина кошка', value: '7513' },
      { label: 'Жесткий секс', value: '2238' },
      { label: 'Жестокие персонажи ', value: '3153' },
      { label: 'Жестокий мир', value: '1532' },
      { label: 'Жестокое обращение с детьми', value: '84' },
      { label: 'Жестокость', value: '7880' },
      { label: 'Животные', value: '7488' },
      { label: 'Животные компаньоны', value: '2061' },
      { label: 'Жизнь и смерть', value: '2014' },
      { label: 'Жнец', value: '6288' },
      { label: 'Жойен рид', value: '3926' },
      { label: 'Заботливый главный герой', value: '338' },
      { label: 'Закалка тела', value: '148' },
      { label: 'Заклинания', value: '558' },
      { label: 'Заключенные', value: '3052' },
      { label: 'Занпакто', value: '1102' },
      { label: 'Запретная любовь', value: '8033' },
      { label: 'Запутанный сюжет', value: '1041' },
      { label: 'Захват мира', value: '315' },
      { label: 'Зачарованные', value: '4169' },
      { label: 'Звери', value: '1638' },
      { label: 'Зверодевочки', value: '2006' },
      { label: 'Зверолюди', value: '1018' },
      { label: 'Земля', value: '82' },
      { label: 'Злая организация', value: '7768' },
      { label: 'Зло', value: '1512' },
      { label: 'Злодей', value: '1060' },
      { label: 'Злодейка', value: '2376' },
      { label: 'Злой главный герой', value: '616' },
      { label: 'Злые боги', value: '7109' },
      { label: 'Злые персонажи', value: '3243' },
      { label: 'Змей', value: '5721' },
      { label: 'Знаменитости', value: '1341' },
      { label: 'Знание медицины', value: '1411' },
      { label: 'Золотой дождь', value: '1828' },
      { label: 'Золушка', value: '2980' },
      { label: 'Зомби', value: '1743' },
      { label: 'Зомби апокалипсис', value: '912' },
      { label: 'Зона 51', value: '3051' },
      { label: 'Зооморфы', value: '375' },
      { label: 'Зоофилия', value: '1165' },
      { label: 'Зорро', value: '6736' },
      { label: 'Зрелые женщины', value: '1458' },
      { label: 'Игра', value: '663' },
      { label: 'Игра на выживание', value: '2182' },
      { label: 'Игровая система', value: '384' },
      { label: 'Игровые элементы', value: '720' },
      { label: 'Извращения', value: '651' },
      { label: 'Измена', value: '1874' },
      { label: 'Изменение характера', value: '1113' },
      { label: 'Изменения внешности', value: '259' },
      { label: 'Изменения личности', value: '1080' },
      { label: 'Изнасилование', value: '1283' },
      { label: 'Изобретения', value: '126' },
      { label: 'Изуку мидория', value: '6967' },
      { label: 'Император', value: '867' },
      { label: 'Империи', value: '712' },
      { label: 'Империя', value: '1716' },
      { label: 'Инвалидность', value: '2073' },
      { label: 'Инквизитор', value: '143' },
      { label: 'Инкуб', value: '3264' },
      { label: 'Инопланетное вторжение', value: '209' },
      { label: 'Инопланетяне', value: '866' },
      { label: 'Интерактив с читателями', value: '472' },
      { label: 'Интересный сюжет', value: '7374' },
      { label: 'Интернет', value: '739' },
      { label: 'Интимные сцены', value: '3450' },
      { label: 'Интрига', value: '317' },
      { label: 'Интриги и заговоры', value: '1009' },
      { label: 'Инцест', value: '1934' },
      { label: 'Иные миры', value: '35' },
      { label: 'Исекай', value: '2979' },
      { label: 'Искусственный интеллект', value: '1900' },
      { label: 'Исследование', value: '1626' },
      { label: 'Исторический роман', value: '573' },
      { label: 'Итачи учиха', value: '4556' },
      { label: 'Ичиго', value: '7254' },
      { label: 'Йода', value: '6829' },
      { label: 'Йоруичи', value: '6755' },
      { label: 'Калипсо', value: '8062' },
      { label: 'Каннибализм', value: '2249' },
      { label: 'Капитан америка', value: '6301' },
      { label: 'Каракура', value: '7473' },
      { label: 'Карточная игра', value: '1557' },
      { label: 'Кастиэль', value: '6954' },
      { label: 'Кафе', value: '3934' },
      { label: 'Кацуки бакуго', value: '7696' },
      { label: 'Квесты', value: '1707' },
      { label: 'Киберпанк', value: '1614' },
      { label: 'Киберспорт', value: '1984' },
      { label: 'Кино', value: '7126' },
      { label: 'Китай', value: '3762' },
      { label: 'Кицунэ', value: '241' },
      { label: 'Кланы', value: '834' },
      { label: 'Клоны', value: '1624' },
      { label: 'Книги', value: '1068' },
      { label: 'Книжный червь', value: '521' },
      { label: 'Колдовство', value: '2681' },
      { label: 'Коллекционер', value: '2588' },
      { label: 'Колледж', value: '5058' },
      { label: 'Кольцо', value: '1628' },
      { label: 'Комедия', value: '1430' },
      { label: 'Коммунисты', value: '1042' },
      { label: 'Коноха', value: '2827' },
      { label: 'Контракт', value: '4304' },
      { label: 'Контроль разума', value: '485' },
      { label: 'Конфеты', value: '341' },
      { label: 'Кончил внутрь', value: '4589' },
      { label: 'Копрофилия', value: '2568' },
      { label: 'Корейцы', value: '6535' },
      { label: 'Корея', value: '2443' },
      { label: 'Королевская власть', value: '55' },
      { label: 'Королевская семья', value: '276' },
      { label: 'Королевство', value: '1695' },
      { label: 'Короткие волосы', value: '8306' },
      { label: 'Короткий рассказ', value: '239' },
      { label: 'Коррупция', value: '831' },
      { label: 'Космическая опера', value: '2245' },
      { label: 'Космические рейнджеры', value: '5860' },
      { label: 'Космос', value: '329' },
      { label: 'Кот', value: '5171' },
      { label: 'Кража навыков', value: '1159' },
      { label: 'Красивая главная героиня', value: '186' },
      { label: 'Красивые женщины', value: '66' },
      { label: 'Красивые персонажи ', value: '5787' },
      { label: 'Красивый главный герой', value: '895' },
      { label: 'Крафт', value: '1599' },
      { label: 'Кровь и расчлененка', value: '7752' },
      { label: 'Кроссовер', value: '75' },
      { label: 'Ксенофилия', value: '2265' },
      { label: 'Ктулху', value: '920' },
      { label: 'Кузнец', value: '853' },
      { label: 'Кукла', value: '3085' },
      { label: 'Кулинария', value: '2230' },
      { label: 'Культивация', value: '1901' },
      { label: 'Культивирование', value: '1860' },
      { label: 'Кунилингус', value: '4651' },
      { label: 'Курама', value: '5709' },
      { label: 'Курилин', value: '6134' },
      { label: 'Кушина узумаки', value: '5222' },
      { label: 'Лавкрафт', value: '6063' },
      { label: 'Лактация', value: '8321' },
      { label: 'Лара крофт', value: '6435' },
      { label: 'Легенда о зельде', value: '5707' },
      { label: 'Ленивый главный герой', value: '1516' },
      { label: 'Леон золдик', value: '7469' },
      { label: 'Лес', value: '6645' },
      { label: 'Лечебная магия', value: '562' },
      { label: 'Литрпг', value: '505' },
      { label: 'Локи', value: '1725' },
      { label: 'Лоли', value: '1576' },
      { label: 'Лопата', value: '4989' },
      { label: 'Лориен', value: '7397' },
      { label: 'Лошади', value: '6110' },
      { label: 'Лунатизм', value: '3520' },
      { label: 'Луффи', value: '274' },
      { label: 'Лучник', value: '1038' },
      { label: 'Любовный интерес влюбляется первым', value: '7753' },
      { label: 'Любовный треугольник', value: '2109' },
      { label: 'Любовь', value: '2297' },
      { label: 'Любовь с первого взгляда', value: '7748' },
      { label: 'Любящие родители', value: '2699' },
      { label: 'Люди', value: '3572' },
      { label: 'Люцифер', value: '5883' },
      { label: 'Маг', value: '780' },
      { label: 'Магазин', value: '4762' },
      { label: 'Маги', value: '58' },
      { label: 'Магическая академия', value: '6788' },
      { label: 'Магические звери', value: '684' },
      { label: 'Магические предметы', value: '1648' },
      { label: 'Магический мир', value: '578' },
      { label: 'Магия', value: '150' },
      { label: 'Магия воды', value: '6450' },
      { label: 'Магия воздуха', value: '7627' },
      { label: 'Магия земли', value: '7626' },
      { label: 'Магия и технология', value: '107' },
      { label: 'Магия крови', value: '7976' },
      { label: 'Магия льда', value: '1379' },
      { label: 'Магия огня', value: '7625' },
      { label: 'Магия призыва', value: '885' },
      { label: 'Магия природы', value: '6226' },
      { label: 'Магия стихий', value: '7673' },
      { label: 'Магия тьмы', value: '3596' },
      { label: 'Мадара', value: '2929' },
      { label: 'Мазохизм', value: '1961' },
      { label: 'Мама', value: '12' },
      { label: 'Мама и дочь', value: '7894' },
      { label: 'Мама и сын', value: '7895' },
      { label: 'Манга', value: '2464' },
      { label: 'Манипуляция временем', value: '932' },
      { label: 'Маньяк', value: '2026' },
      { label: 'Марвел', value: '8328' },
      { label: 'Маргери тирелл', value: '3935' },
      { label: 'Марионетки', value: '3175' },
      { label: 'Марс', value: '4013' },
      { label: 'Марти стью', value: '594' },
      { label: 'Мастер на все руки', value: '3189' },
      { label: 'Мастурбация', value: '3078' },
      { label: 'Матриархат', value: '7197' },
      { label: 'Мать и сестры', value: '7946' },
      { label: 'Мафия', value: '353' },
      { label: 'Мачеха', value: '4664' },
      { label: 'Мегаполис', value: '3322' },
      { label: 'Медицина', value: '441' },
      { label: 'Медленное развитие истории', value: '7462' },
      { label: 'Медленный роман', value: '8309' },
      { label: 'Межрасовый секс', value: '3489' },
      { label: 'Мелиодас', value: '7224' },
      { label: 'Мелодрама', value: '1507' },
      { label: 'Менеджмент', value: '368' },
      { label: 'Мерлин', value: '3977' },
      { label: 'Месть', value: '1218' },
      { label: 'Меха', value: '2303' },
      { label: 'Меч', value: '48' },
      { label: 'Мечники', value: '969' },
      { label: 'Мечта', value: '527' },
      { label: 'Мизуки', value: '4269' },
      { label: 'Микото', value: '3862' },
      { label: 'Милая главная героиня', value: '134' },
      { label: 'Милф', value: '1987' },
      { label: 'Милый главный герой', value: '2678' },
      { label: 'Мимик', value: '5706' },
      { label: 'Мина ашидо', value: '7695' },
      { label: 'Минато намикадзе', value: '5223' },
      { label: 'Минет', value: '3289' },
      { label: 'Мир будущего', value: '1770' },
      { label: 'Мир меча и магии', value: '1271' },
      { label: 'Мистер пропер', value: '565' },
      { label: 'Мистика', value: '510' },
      { label: 'Мифические существа', value: '1878' },
      { label: 'Мифы и легенды', value: '4463' },
      { label: 'Младшая сестра', value: '1523' },
      { label: 'Мморпг', value: '620' },
      { label: 'Много главных героев', value: '1191' },
      { label: 'Много крови', value: '5318' },
      { label: 'Много персонажей', value: '1539' },
      { label: 'Множество королевств', value: '32' },
      { label: 'Мо', value: '8307' },
      { label: 'Модерн', value: '5457' },
      { label: 'Мокутон', value: '4438' },
      { label: 'Молоко', value: '5469' },
      { label: 'Монархия', value: '3590' },
      { label: 'Монстры', value: '307' },
      { label: 'Море', value: '922' },
      { label: 'Моритика ринносукэ', value: '1142' },
      { label: 'Мортал комбат', value: '5861' },
      { label: 'Мошенник', value: '959' },
      { label: 'Мрачный мир', value: '1' },
      { label: 'Мужчина протагонист', value: '31' },
      { label: 'Музыка', value: '1183' },
      { label: 'Мультивселенная', value: '7410' },
      { label: 'Мурим', value: '7342' },
      { label: 'Мутанты', value: '2392' },
      { label: 'Мутация', value: '29' },
      { label: 'Мясо', value: '1503' },
      { label: 'На реальных событиях', value: '26' },
      { label: 'Навыки', value: '415' },
      { label: 'Нагато узумаки', value: '5221' },
      { label: 'Наемники', value: '1668' },
      { label: 'Назарик', value: '5369' },
      { label: 'Наивный главный герой', value: '159' },
      { label: 'Наложница', value: '4867' },
      { label: 'Наноботы', value: '2332' },
      { label: 'Наркотики', value: '1436' },
      { label: 'Наруто', value: '7177' },
      { label: 'Наруто и хината', value: '5766' },
      { label: 'Насилие и жестокость', value: '1440' },
      { label: 'Наука', value: '2150' },
      { label: 'Научная фантастика', value: '2244' },
      { label: 'Национализм', value: '5556' },
      { label: 'Нацу', value: '5826' },
      { label: 'Нацуки субару', value: '6656' },
      { label: 'Начальная школа', value: '3920' },
      { label: 'Наши дни', value: '1814' },
      { label: 'Не всесильный главный герой', value: '42' },
      { label: 'Не по канону', value: '1611' },
      { label: 'Неверность', value: '5735' },
      { label: 'Невеста', value: '6011' },
      { label: 'Неджи хьюга', value: '3099' },
      { label: 'Недооценённый главный герой', value: '43' },
      { label: 'Нежить', value: '1949' },
      { label: 'Некромаг', value: '7441' },
      { label: 'Некромант', value: '1914' },
      { label: 'Некромантия', value: '754' },
      { label: 'Некрофилия', value: '1285' },
      { label: 'Ненормативная лексика', value: '160' },
      { label: 'Необычные герои', value: '67' },
      { label: 'Нет людей', value: '7486' },
      { label: 'Нетораре', value: '403' },
      { label: 'Нетори', value: '5393' },
      { label: 'Нефилимы', value: '7764' },
      { label: 'Нецензурная лексика', value: '4912' },
      { label: 'Нечисть', value: '4559' },
      { label: 'Ник фьюри', value: '6304' },
      { label: 'Ниндзюцу', value: '2354' },
      { label: 'Ниндзя', value: '1330' },
      { label: 'Новелла', value: '2105' },
      { label: 'Нудизм', value: '2233' },
      { label: 'Нэко', value: '147' },
      { label: 'Оби ван кеноби', value: '6830' },
      { label: 'Обито учиха', value: '2814' },
      { label: 'Оборотни', value: '53' },
      { label: 'Обратный гарем', value: '3303' },
      { label: 'Овощ', value: '6098' },
      { label: 'Огнестрельное оружие', value: '3155' },
      { label: 'Одержимость', value: '708' },
      { label: 'Один в поле воин', value: '6498' },
      { label: 'Омегаверс', value: '8334' },
      { label: 'омегаверс', value: '8322' },
      { label: 'Онлайн игра', value: '1565' },
      { label: 'Ооками теппей', value: '849' },
      { label: 'Оральный секс', value: '605' },
      { label: 'Оргия', value: '974' },
      { label: 'Оригинальные персонажи', value: '7741' },
      { label: 'Орки', value: '1597' },
      { label: 'Оружие', value: '125' },
      { label: 'Основано на видео игре', value: '602' },
      { label: 'Особые способности', value: '2904' },
      { label: 'От бедности к богатству', value: '901' },
      { label: 'От слабого до сильного', value: '118' },
      { label: 'Отель', value: '2879' },
      { label: 'Отец', value: '3290' },
      { label: 'Отношения', value: '398' },
      { label: 'Отношения человек/нечеловек', value: '7406' },
      { label: 'Офис', value: '3460' },
      { label: 'Охотники', value: '2263' },
      { label: 'Оценки', value: '8305' },
      { label: 'Оцуцуки', value: '5101' },
      { label: 'Ошейник', value: '2362' },
      { label: 'Ояш', value: '8048' },
      { label: 'Падчерица', value: '7023' },
      { label: 'Падший ангел', value: '184' },
      { label: 'Пайзури', value: '3560' },
      { label: 'Палач', value: '852' },
      { label: 'Палочка', value: '2682' },
      { label: 'Пандорум', value: '4360' },
      { label: 'Папа и дочь', value: '7647' },
      { label: 'Паразит', value: '1213' },
      { label: 'Параллельный мир', value: '2092' },
      { label: 'Парень', value: '619' },
      { label: 'Паркур', value: '3391' },
      { label: 'Пародия', value: '898' },
      { label: 'Пасхалки', value: '455' },
      { label: 'Паук', value: '2209' },
      { label: 'Педофилия', value: '7052' },
      { label: 'Пекарь', value: '5073' },
      { label: 'Первая книга', value: '269' },
      { label: 'Первая любовь', value: '640' },
      { label: 'Первый раз', value: '1465' },
      { label: 'Переводы', value: '24' },
      { label: 'Перевоплощение', value: '1596' },
      { label: 'Перевоплощение в игровом мире', value: '92' },
      { label: 'Перемещение в другой мир', value: '1288' },
      { label: 'Перемещение во времени', value: '146' },
      { label: 'Перерождение', value: '894' },
      { label: 'Перерождение в демона', value: '1111' },
      { label: 'Перерождение в дракона', value: '6867' },
      { label: 'Перерождение в злодейку', value: '5619' },
      { label: 'Перерождение в злодея', value: '749' },
      { label: 'Перерождение в ином мире', value: '109' },
      { label: 'Перерождение в монстра', value: '917' },
      { label: 'Перерождений', value: '335' },
      { label: 'Переселение', value: '813' },
      { label: 'Переселение души', value: '1864' },
      { label: 'Перси джексон', value: '6329' },
      { label: 'Пилот', value: '5521' },
      { label: 'Пилюли', value: '1531' },
      { label: 'Пират', value: '1579' },
      { label: 'Пирог', value: '80' },
      { label: 'Писатель', value: '734' },
      { label: 'Пистолеты', value: '4916' },
      { label: 'Письмо', value: '840' },
      { label: 'Питомцы', value: '3122' },
      { label: 'Планомерное развитие событий', value: '62' },
      { label: 'Племянник', value: '8303' },
      { label: 'Пленница', value: '4897' },
      { label: 'Плети', value: '4839' },
      { label: 'Пляж', value: '4243' },
      { label: 'Повар', value: '658' },
      { label: 'Повествование от первого лица', value: '1054' },
      { label: 'Повествование от разных лиц', value: '600' },
      { label: 'Повествование от третьего лица', value: '2116' },
      { label: 'Повседневность', value: '802' },
      { label: 'Подавитель', value: '497' },
      { label: 'Подземелье', value: '798' },
      { label: 'Подростки', value: '636' },
      { label: 'Подруга', value: '5804' },
      { label: 'Подчинение и унижение', value: '4500' },
      { label: 'Покемон', value: '8333' },
      { label: 'Покемоны', value: '2840' },
      { label: 'Полиамория', value: '1300' },
      { label: 'Полигамия', value: '1336' },
      { label: 'Политика', value: '1313' },
      { label: 'Полицейский', value: '1907' },
      { label: 'Полубог', value: '7170' },
      { label: 'Полукровка', value: '999' },
      { label: 'Полулюди', value: '2273' },
      { label: 'Поношенные трусики', value: '1204' },
      { label: 'Попаданец', value: '2396' },
      { label: 'Попаданец в другой мир', value: '685' },
      { label: 'Попаданец в игру', value: '6466' },
      { label: 'Попадание в книгу', value: '6957' },
      { label: 'Порно', value: '4023' },
      { label: 'Постапокалипсис', value: '1079' },
      { label: 'Потеря девственности', value: '5879' },
      { label: 'Похищение', value: '7452' },
      { label: 'Поэзия', value: '1120' },
      { label: 'Правитель', value: '2261' },
      { label: 'Превращени', value: '8311' },
      { label: 'Превращения в животных', value: '3410' },
      { label: 'Преданный любовный интерес', value: '2055' },
      { label: 'Предательство', value: '70' },
      { label: 'Президент', value: '4334' },
      { label: 'Преступник', value: '4049' },
      { label: 'Преступный мир', value: '965' },
      { label: 'Призрак', value: '511' },
      { label: 'Призыв', value: '332' },
      { label: 'Призыв в другой мир', value: '781' },
      { label: 'Призыв существ', value: '412' },
      { label: 'Приключения', value: '964' },
      { label: 'Приложение на телефоне', value: '5345' },
      { label: 'Принудительный брак', value: '2954' },
      { label: 'Принуждение', value: '1442' },
      { label: 'Принц', value: '362' },
      { label: 'Принцесса', value: '2403' },
      { label: 'Приручение мостров', value: '2338' },
      { label: 'Прислуга', value: '5185' },
      { label: 'Пришельцы', value: '273' },
      { label: 'Проза', value: '2012' },
      { label: 'Прокачка', value: '1070' },
      { label: 'Проклятия', value: '1347' },
      { label: 'Проработанный мир', value: '1711' },
      { label: 'Пророчество', value: '7762' },
      { label: 'Проститутки', value: '8325' },
      { label: 'Протагонист влюбляется первый', value: '8315' },
      { label: 'Псайкеры', value: '3659' },
      { label: 'Псионика', value: '5216' },
      { label: 'Психбольница', value: '6969' },
      { label: 'Психические расстройства', value: '2445' },
      { label: 'Психологические травмы', value: '3418' },
      { label: 'Психология', value: '17' },
      { label: 'Публичный дом', value: '7860' },
      { label: 'Публичный секс', value: '6647' },
      { label: 'Путешествие в другой мир', value: '10' },
      { label: 'Путешествие во времени', value: '8308' },
      { label: 'Пух', value: '4286' },
      { label: 'Пушечное мясо', value: '7234' },
      { label: 'Пытки', value: '1756' },
      { label: 'Пьяный мастер', value: '1655' },
      { label: 'Пэнси паркинсон', value: '7411' },
      { label: 'Раб', value: '977' },
      { label: 'Рабы', value: '1240' },
      { label: 'Разведение животных', value: '3990' },
      { label: 'Развитие', value: '208' },
      { label: 'Развитие персонажа', value: '1780' },
      { label: 'Развитие поселения', value: '7203' },
      { label: 'Развитие технологий', value: '1875' },
      { label: 'Разврат', value: '1924' },
      { label: 'Разговор в комнате', value: '8302' },
      { label: 'Раздвоение личности', value: '2062' },
      { label: 'Разные расы', value: '1188' },
      { label: 'Разный социальный статус', value: '8314' },
      { label: 'Разорванная помолвка', value: '2057' },
      { label: 'Разработчик', value: '2333' },
      { label: 'Ранги', value: '1568' },
      { label: 'Ранобэ', value: '1764' },
      { label: 'Расизм', value: '3554' },
      { label: 'Растение', value: '407' },
      { label: 'Расчленение', value: '7125' },
      { label: 'Реализм', value: '1180' },
      { label: 'Реанкарнация', value: '206' },
      { label: 'Ребенок', value: '2881' },
      { label: 'Ревность', value: '293' },
      { label: 'Революция', value: '3996' },
      { label: 'Реинкарнация', value: '1302' },
      { label: 'Реинкарнация в другом мире', value: '2180' },
      { label: 'Реинкарнация в игровой мир', value: '304' },
      { label: 'Рейджер', value: '5147' },
      { label: 'Религия', value: '2184' },
      { label: 'Рем', value: '6655' },
      { label: 'Ремесленник', value: '1483' },
      { label: 'Ремонт', value: '5703' },
      { label: 'Репликаторы', value: '3495' },
      { label: 'Ресторан', value: '7519' },
      { label: 'Риас гремори', value: '6950' },
      { label: 'Рим', value: '612' },
      { label: 'Риннеган', value: '4230' },
      { label: 'Ритуал', value: '1233' },
      { label: 'Робот', value: '4011' },
      { label: 'Роботы', value: '467' },
      { label: 'Рок ли', value: '7002' },
      { label: 'Рокси', value: '7380' },
      { label: 'Романтика', value: '1025' },
      { label: 'Рон уизли', value: '4279' },
      { label: 'Ророноа зоро', value: '1590' },
      { label: 'Росомаха', value: '1035' },
      { label: 'Российская империя', value: '2146' },
      { label: 'Россия', value: '4246' },
      { label: 'Рудеус', value: '7379' },
      { label: 'Руны', value: '2393' },
      { label: 'Русалки', value: '3127' },
      { label: 'Русь', value: '2016' },
      { label: 'Рыцари', value: '1902' },
      { label: 'Рэо хатаке', value: '2823' },
      { label: 'Сабли', value: '6136' },
      { label: 'Сайян', value: '6802' },
      { label: 'Сакура', value: '2515' },
      { label: 'Самец', value: '1592' },
      { label: 'Самоубийство', value: '4312' },
      { label: 'Самураи', value: '576' },
      { label: 'Санса старк', value: '3925' },
      { label: 'Сарказм', value: '4658' },
      { label: 'Саске', value: '7237' },
      { label: 'Сатира', value: '215' },
      { label: 'Сборник', value: '7367' },
      { label: 'Свадьба', value: '1524' },
      { label: 'Сверхсила', value: '1055' },
      { label: 'Сверхъестественное', value: '1074' },
      { label: 'Свингеры', value: '514' },
      { label: 'Свинцовые книги', value: '5322' },
      { label: 'Связывание', value: '4506' },
      { label: 'Священик', value: '61' },
      { label: 'Северус снейп', value: '5783' },
      { label: 'Сёдзе', value: '2219' },
      { label: 'Секс', value: '2472' },
      { label: 'Секс без проникновения', value: '151' },
      { label: 'Секс игрушки', value: '1124' },
      { label: 'Секс по согласию', value: '7307' },
      { label: 'Секс рабыня', value: '7174' },
      { label: 'Секс с близнецами', value: '7457' },
      { label: 'Секс с монстрами', value: '6073' },
      { label: 'Секс с учителем', value: '2570' },
      { label: 'Секса будет много', value: '7265' },
      { label: 'Сексуальные и психологические отклонения', value: '888' },
      { label: 'Секты', value: '1234' },
      { label: 'Селфцест', value: '7498' },
      { label: 'Сельское хозяйство', value: '787' },
      { label: 'Семейный конфликт', value: '935' },
      { label: 'Семья', value: '728' },
      { label: 'Сенджу', value: '6069' },
      { label: 'Сёнэн', value: '2058' },
      { label: 'Серийный убийца', value: '261' },
      { label: 'Сестра', value: '2342' },
      { label: 'Сила глаза', value: '1019' },
      { label: 'Сильная героиня', value: '7292' },
      { label: 'Сильная главная героиня', value: '1994' },
      { label: 'Сильный главный герой', value: '570' },
      { label: 'Сильфиетта', value: '7381' },
      { label: 'Симбиот', value: '2648' },
      { label: 'Сириус блэк', value: '7655' },
      { label: 'Сирота', value: '297' },
      { label: 'Система', value: '251' },
      { label: 'Система уровней', value: '2174' },
      { label: 'Сиськи', value: '16' },
      { label: 'Ситх', value: '1618' },
      { label: 'Сказка', value: '3570' },
      { label: 'Скайрим', value: '4032' },
      { label: 'Скайуокер', value: '6828' },
      { label: 'Сквиб', value: '4101' },
      { label: 'Сквирт', value: '4526' },
      { label: 'Скелет', value: '1315' },
      { label: 'Скрытые способности', value: '3417' },
      { label: 'Скульптор', value: '1178' },
      { label: 'Слабая главная героиня', value: '5805' },
      { label: 'Слабый главный герой', value: '731' },
      { label: 'Славяне', value: '2168' },
      { label: 'Слизерин', value: '6979' },
      { label: 'Слизь', value: '1095' },
      { label: 'Служанка', value: '3486' },
      { label: 'Смартфон', value: '457' },
      { label: 'Смерть', value: '1779' },
      { label: 'Смерть близких', value: '8312' },
      { label: 'Смерть основного персонажа', value: '1530' },
      { label: 'Собаки', value: '6109' },
      { label: 'Соблазн', value: '7994' },
      { label: 'Соблазнение', value: '2290' },
      { label: 'Современность', value: '568' },
      { label: 'Современные знания', value: '988' },
      { label: 'Сожительство', value: '3026' },
      { label: 'Создание армии', value: '1992' },
      { label: 'Создание королевства', value: '1497' },
      { label: 'Создание пилюль', value: '816' },
      { label: 'Создатель', value: '1045' },
      { label: 'Сокровища', value: '6521' },
      { label: 'Сокрытие истинной личности', value: '2894' },
      { label: 'Сома и эрина', value: '5737' },
      { label: 'Соперничество', value: '7699' },
      { label: 'Соседи', value: '4075' },
      { label: 'Сотрудник', value: '6339' },
      { label: 'Социология', value: '7618' },
      { label: 'Спокойная главная героиня', value: '236' },
      { label: 'Спокойный главный герой', value: '1656' },
      { label: 'Спор', value: '3484' },
      { label: 'Спорт', value: '1387' },
      { label: 'Спортивное тело', value: '8317' },
      { label: 'Способность кражи', value: '7784' },
      { label: 'Сражения', value: '23' },
      { label: 'Средневековье', value: '1022' },
      { label: 'Сталкер', value: '1932' },
      { label: 'Становление государства', value: '111' },
      { label: 'Старшая школа', value: '1658' },
      { label: 'Стёб', value: '454' },
      { label: 'Стекло', value: '7453' },
      { label: 'Стеснительный персонаж', value: '152' },
      { label: 'Стимпанк', value: '1894' },
      { label: 'Стихи', value: '1309' },
      { label: 'Стратегия', value: '569' },
      { label: 'Стриптиз', value: '6914' },
      { label: 'Строительство', value: '921' },
      { label: 'Студент', value: '1464' },
      { label: 'Студентка', value: '7518' },
      { label: 'Суккубы', value: '2662' },
      { label: 'Супер зрение', value: '6574' },
      { label: 'Супер удача', value: '489' },
      { label: 'Супергерои', value: '1481' },
      { label: 'Суперзлодеи', value: '2125' },
      { label: 'Супермен', value: '6997' },
      { label: 'Суперсилы', value: '2276' },
      { label: 'Существа', value: '6033' },
      { label: 'Сферы', value: '1077' },
      { label: 'Схемы и заговоры', value: '7116' },
      { label: 'Сценарий', value: '7489' },
      { label: 'Счастливый конец', value: '3293' },
      { label: 'Сын', value: '3297' },
      { label: 'Сэйнэн', value: '345' },
      { label: 'Сэм винчестер', value: '7461' },
      { label: 'Сюаньхуа', value: '2560' },
      { label: 'Сюжетные повороты', value: '7202' },
      { label: 'Сянься', value: '1126' },
      { label: 'Таблетки для развития', value: '589' },
      { label: 'Табу', value: '8304' },
      { label: 'Таинственное прошлое', value: '769' },
      { label: 'Тайная личность', value: '8096' },
      { label: 'Тайная любовь', value: '113' },
      { label: 'Тайны', value: '7481' },
      { label: 'Тайные отношения', value: '7450' },
      { label: 'Тайцы', value: '6413' },
      { label: 'Танки', value: '1787' },
      { label: 'Твинцест', value: '2450' },
      { label: 'Творчество', value: '20' },
      { label: 'Тейлор эберт', value: '3526' },
      { label: 'Телекинез', value: '2203' },
      { label: 'Телепортация', value: '914' },
      { label: 'Телохранитель', value: '723' },
      { label: 'Темари', value: '4810' },
      { label: 'Темная магия', value: '4788' },
      { label: 'Темное фэнтези', value: '1675' },
      { label: 'Темные эльфы', value: '7198' },
      { label: 'Тенсейган', value: '4367' },
      { label: 'Тентакли', value: '3236' },
      { label: 'Тетя', value: '4194' },
      { label: 'Техномагия', value: '508' },
      { label: 'Тиран', value: '1174' },
      { label: 'Титаны', value: '3308' },
      { label: 'Тодороки шото', value: '5105' },
      { label: 'Токио', value: '5791' },
      { label: 'Том реддл', value: '6652' },
      { label: 'Тони старк', value: '1338' },
      { label: 'Тор', value: '1800' },
      { label: 'Тор и локи', value: '2645' },
      { label: 'Торговля', value: '1637' },
      { label: 'Травничество', value: '221' },
      { label: 'Трагедия', value: '470' },
      { label: 'Трагическое прошлое', value: '644' },
      { label: 'Трактир', value: '1918' },
      { label: 'Трансмиграция', value: '1071' },
      { label: 'Трансформация', value: '156' },
      { label: 'Трансформеры', value: '4616' },
      { label: 'Тревор филипс', value: '5427' },
      { label: 'Триллер', value: '1676' },
      { label: 'Тройняшки', value: '7169' },
      { label: 'Троли', value: '4250' },
      { label: 'Трудолюбивый главный герой', value: '248' },
      { label: 'Тупой главный герой', value: '3710' },
      { label: 'Тьма', value: '1919' },
      { label: 'Тюрьма', value: '5597' },
      { label: 'Тяжёлое детство', value: '2253' },
      { label: 'Убийства', value: '378' },
      { label: 'Убийцы', value: '1766' },
      { label: 'Убийцы драконов', value: '1484' },
      { label: 'Увечья', value: '3266' },
      { label: 'Удача', value: '6575' },
      { label: 'Ужасы', value: '1747' },
      { label: 'Узумаки', value: '7579' },
      { label: 'Укротитель', value: '367' },
      { label: 'Умения', value: '531' },
      { label: 'Умная главная героиня', value: '1381' },
      { label: 'Умные персонажи', value: '2756' },
      { label: 'Умный главный герой', value: '2093' },
      { label: 'Университет', value: '2102' },
      { label: 'Уничтожение мира', value: '81' },
      { label: 'Управление временем', value: '5648' },
      { label: 'Уровни', value: '8' },
      { label: 'Усиление', value: '3549' },
      { label: 'Усопп', value: '6737' },
      { label: 'Устроенный брак', value: '2223' },
      { label: 'Усыновление', value: '395' },
      { label: 'Уся', value: '1172' },
      { label: 'Утопия', value: '4677' },
      { label: 'Уход за детьми', value: '7609' },
      { label: 'Учеба в университете', value: '2797' },
      { label: 'Учебное заведение', value: '1817' },
      { label: 'Ученые', value: '1843' },
      { label: 'Учитель', value: '845' },
      { label: 'Учиха', value: '5348' },
      { label: 'Фамильяры', value: '1471' },
      { label: 'Фанатичная любовь', value: '6721' },
      { label: 'Фанаты', value: '7739' },
      { label: 'Фантастика', value: '286' },
      { label: 'Фантастический мир', value: '2414' },
      { label: 'Фанфик', value: '767' },
      { label: 'Фармацевт', value: '1706' },
      { label: 'Фашисты', value: '3118' },
      { label: 'Феи', value: '7185' },
      { label: 'Фелляция', value: '5880' },
      { label: 'Феминизм', value: '6527' },
      { label: 'Феникс', value: '2413' },
      { label: 'Фенрир', value: '2740' },
      { label: 'Феодализм', value: '280' },
      { label: 'Ферма', value: '285' },
      { label: 'Фетиш', value: '2398' },
      { label: 'Фехтовальщик', value: '4685' },
      { label: 'Филиппины', value: '128' },
      { label: 'Философия', value: '1859' },
      { label: 'Фистинг', value: '4206' },
      { label: 'Флафф', value: '5048' },
      { label: 'Флер делакур', value: '5191' },
      { label: 'Флэш', value: '4667' },
      { label: 'Фокусник', value: '7602' },
      { label: 'Фольклор', value: '4086' },
      { label: 'Фугаку', value: '6161' },
      { label: 'Фурри', value: '6631' },
      { label: 'Футбол', value: '1121' },
      { label: 'Фэнтези', value: '174' },
      { label: 'Фэнтезийный мир', value: '1556' },
      { label: 'Хакер', value: '475' },
      { label: 'Халк', value: '1196' },
      { label: 'Хан нуньен синг', value: '4817' },
      { label: 'Ханма юджиро', value: '4369' },
      { label: 'Хаос', value: '3117' },
      { label: 'Харизматичный главный герой', value: '2350' },
      { label: 'Хатаке какаши', value: '2820' },
      { label: 'Хентай', value: '1682' },
      { label: 'Хиддлстон', value: '5903' },
      { label: 'Химавари', value: '2583' },
      { label: 'Хината', value: '2513' },
      { label: 'Хитрый главный герой', value: '2036' },
      { label: 'Хоббит', value: '6698' },
      { label: 'Хогвартс', value: '5954' },
      { label: 'Холодная главная героиня', value: '6507' },
      { label: 'Холодное оружие', value: '4889' },
      { label: 'Холодный главный герой', value: '2686' },
      { label: 'Храм', value: '2135' },
      { label: 'Христианство', value: '877' },
      { label: 'Художественная литература', value: '2380' },
      { label: 'Художница', value: '518' },
      { label: 'Хулиганы', value: '854' },
      { label: 'Цветок', value: '902' },
      { label: 'Цезарь', value: '1705' },
      { label: 'Целители', value: '4523' },
      { label: 'Церковь', value: '1980' },
      { label: 'Цундере', value: '1078' },
      { label: 'Чакра', value: '1393' },
      { label: 'Черная пантера', value: '8330' },
      { label: 'Черный юмор', value: '2868' },
      { label: 'Честная главная героиня', value: '5855' },
      { label: 'Честный главный герой', value: '129' },
      { label: 'Читы', value: '451' },
      { label: 'Шантаж', value: '7175' },
      { label: 'Шаринган', value: '5165' },
      { label: 'Шинигами', value: '4661' },
      { label: 'Шиноби', value: '1227' },
      { label: 'Школьная жизнь', value: '284' },
      { label: 'Школьники', value: '218' },
      { label: 'Школьницы', value: '5946' },
      { label: 'Шлюха', value: '5822' },
      { label: 'Шоу-бизнес', value: '7119' },
      { label: 'Шпионы', value: '4262' },
      { label: 'Эволюция', value: '2040' },
      { label: 'Экзорцизм', value: '676' },
      { label: 'Экономика', value: '121' },
      { label: 'Эксгибиционизм', value: '1643' },
      { label: 'Экспансия', value: '110' },
      { label: 'Эксперименты над людьми', value: '7408' },
      { label: 'Экшен', value: '2859' },
      { label: 'Элементальная магия', value: '1264' },
      { label: 'Элементы бдсм', value: '1323' },
      { label: 'Элементы рпг', value: '8316' },
      { label: 'Эльфы', value: '1362' },
      { label: 'Эротика', value: '2053' },
      { label: 'Этти', value: '1317' },
      { label: 'Юмор', value: '7360' },
      { label: 'Яды', value: '201' },
      { label: 'Якудза', value: '4599' },
      { label: 'Яндере', value: '7111' },
      { label: '12+', value: '3316' },
      { label: '16+', value: '83' },
      { label: '18+', value: '1749' },
      { label: '21+', value: '3191' },
      { label: 'Bdsm', value: '8320' },
      { label: 'Bl', value: '8282' },
      { label: 'Bo', value: '8318' },
      { label: 'Gl', value: '8284' },
      { label: 'Marvel', value: '8329' },
      { label: 'Rpg', value: '90' },
      { label: 'Star wars', value: '1985' },
      { label: 'Time skip', value: '824' },
      { label: 'Warrior of light', value: '5289' },
    ],
    inputType: FilterInputs.Checkbox,
  },
  {
    key: 'adult',
    label: 'Возрастные ограничения',
    values: [
      { label: 'Все', value: '0' },
      { label: 'Убрать 18+', value: '1' },
      { label: 'Только 18+', value: '2' },
    ],
    inputType: FilterInputs.Picker,
  },
];

const RulateLibScraper = {
  popularNovels,
  parseNovelAndChapters,
  parseChapter,
  searchNovels,
  filters,
};

export default RulateLibScraper;
