import { FilterInputs } from '../types/filterTypes';
import { Status } from '../helpers/constants';
import * as cheerio from 'cheerio';
import { defaultTo } from 'lodash';

const sourceId = 118;
const sourceName = 'Rulate';

const baseUrl = 'https://tl.rulate.ru';

const popularNovels = async (page, { showLatestNovels, filters }) => {
  let url = baseUrl + '/search?t=&cat=2';
  url += '&sort=' + defaultTo(filters?.sort, showLatestNovels ? '4' : '6');
  url += '&type=' + defaultTo(filters?.type, '0');
  url += '&atmosphere=' + defaultTo(filters?.atmosphere, '0');
  url += '&adult=' + defaultTo(filters?.adult, '0');

  if (filters?.genres?.length) {
    url += filters.genres.map(i => `&genres[]=${i}`).join('');
  }

  if (filters?.tags?.length) {
    url += filters.tags.map(i => `&tags[]=${i}`).join('');
  }

  if (filters?.trash?.length) {
    url += filters.trash.map(i => `&${i}=1`);
  }

  url += `&Book_page=${page}`;

  const result = await fetch(url);
  const body = await result.text();
  const loadedCheerio = cheerio.load(body);
  const totalPages = parseInt(
    loadedCheerio('div[class="pagination"] > ul > li:last-child > a')
      .attr('href')
      .split('/Book_page/')[1] || '250',
    10,
  );
  let novels = [];

  loadedCheerio(
    'ul[class="search-results"] > li:not([class="ad_type_catalog"])',
  ).each(function () {
    const novelName = loadedCheerio(this).find('p > a').text();
    const novelCover = baseUrl + loadedCheerio(this).find('img').attr('src');
    const novelUrl = loadedCheerio(this).find('p > a').attr('href');

    const novel = { sourceId, novelName, novelCover, novelUrl };
    novels.push(novel);
  });

  return { totalPages, novels };
};

const parseNovelAndChapters = async novelUrl => {
  let result = await fetch(baseUrl + novelUrl);
  if (result.url.includes('mature?path=')) {
    const formData = new FormData();
    formData.append('path', novelUrl);
    formData.append('ok', 'Да');

    await fetch(result.url, {
      method: 'POST',
      body: formData,
    });

    result = await fetch(baseUrl + novelUrl);
  }
  const body = await result.text();
  const loadedCheerio = cheerio.load(body);

  let novel = {
    sourceId,
    sourceName,
    url: baseUrl + novelUrl,
    novelUrl,
  };

  novel.novelName = loadedCheerio('div[class="container"] > div > div > h1')
    .text()
    .trim();
  novel.novelCover =
    baseUrl + loadedCheerio('div[class="images"] > div img').attr('src');
  novel.summary = loadedCheerio('#Info > div:nth-child(3)').text().trim();
  novel.genre = [];

  let chapters = [];

  loadedCheerio('div[class="span5"] > p').each(function () {
    switch (loadedCheerio(this).find('strong').text()) {
      case 'Автор:':
        novel.author = loadedCheerio(this).find('em > a').text().trim();
        break;
      case 'Выпуск:':
        novel.status =
          loadedCheerio(this).find('em').text().trim() === 'продолжается'
            ? Status.ONGOING
            : Status.COMPLETED;
        break;
      case 'Тэги:':
        loadedCheerio(this)
          .find('em > a')
          .each(function () {
            novel.genre.push(loadedCheerio(this).text());
          });
        break;
      case 'Жанры:':
        loadedCheerio(this)
          .find('em > a')
          .each(function () {
            novel.genre.push(loadedCheerio(this).text());
          });
        break;
    }
  });

  if (novel.genre.length > 0) {
    novel.genre = novel.genre.reverse().join(',');
  } else {
    novel.genre = '';
  }

  loadedCheerio('table > tbody > tr.chapter_row').each(function () {
    const chapterName = loadedCheerio(this)
      .find('td[class="t"] > a')
      .text()
      .trim();
    const releaseDate = null;
    const chapterUrl = loadedCheerio(this)
      .find('td[class="t"] > a')
      .attr('href');

    if (loadedCheerio(this).find('td > span[class="disabled"]').length < 1) {
      chapters.push({ chapterName, releaseDate, chapterUrl });
    }
  });

  novel.chapters = chapters;
  return novel;
};

const parseChapter = async (novelUrl, chapterUrl) => {
  let result = await fetch(baseUrl + chapterUrl);
  if (result.url.includes('mature?path=')) {
    const formData = new FormData();
    formData.append('path', novelUrl);
    formData.append('ok', 'Да');

    await fetch(result.url, {
      method: 'POST',
      body: formData,
    });

    result = await fetch(baseUrl + chapterUrl);
  }
  const body = await result.text();
  const loadedCheerio = cheerio.load(body);

  loadedCheerio('.content-text img').each(function () {
    if (!loadedCheerio(this).attr('src')?.startsWith('http')) {
      const src = loadedCheerio(this).attr('src');
      loadedCheerio(this).attr('src', baseUrl + src);
    }
  });

  const chapterName = loadedCheerio(
    '.chapter_select > select > option[selected]',
  )
    .text()
    .trim();
  const chapterText = loadedCheerio('.content-text').html();

  const chapter = {
    sourceId,
    novelUrl,
    chapterUrl,
    chapterName,
    chapterText,
  };

  return chapter;
};

const searchNovels = async searchTerm => {
  const result = await fetch(
    baseUrl + '/search/autocomplete?query=' + searchTerm,
  );
  let json = await result.json();
  let novels = [];

  json.map(item => {
    const novelName = item.title_one + ' / ' + item.title_two;
    const novelCover = baseUrl + item.img;
    const novelUrl = item.url;

    novels.push({ sourceId, novelName, novelCover, novelUrl });
  });

  return novels;
};

const filters = [
  {
    key: 'sort',
    label: 'Сортировка',
    values: [
      { label: 'По рейтингу', value: '6' },
      { label: 'По степени готовности', value: '0' },
      { label: 'По названию на языке оригинала', value: '1' },
      { label: 'По названию на языке перевода', value: '2' },
      { label: 'По дате создания', value: '3' },
      { label: 'По дате последней активности', value: '4' },
      { label: 'По просмотрам', value: '5' },
      { label: 'По кол-ву переведённых глав', value: '7' },
      { label: 'По кол-ву лайков', value: '8' },
      { label: 'По кол-ву страниц', value: '10' },
      { label: 'По кол-ву бесплатных глав', value: '11' },
      { label: 'По кол-ву рецензий', value: '12' },
      { label: 'По кол-ву в закладках', value: '13' },
      { label: 'По кол-ву в избранном', value: '14' },
    ],
    inputType: FilterInputs.Picker,
  },
  {
    key: 'type',
    label: 'Тип',
    values: [
      { label: 'Неважно', value: '0' },
      { label: 'Только переводы', value: '1' },
      { label: 'Только авторские', value: '2' },
    ],
    inputType: FilterInputs.Picker,
  },

  {
    key: 'atmosphere',
    label: 'Атмосфера',
    values: [
      { label: 'Неважно', value: '0' },
      { label: 'Позитивная', value: '1' },
      { label: 'Dark', value: '2' },
    ],
    inputType: FilterInputs.Picker,
  },
  {
    key: 'trash',
    label: 'Другое',
    values: [
      { label: 'Готовые на 100%', value: 'ready' },
      { label: 'Доступные для скачивания', value: 'gen' },
      { label: 'Доступные для перевода', value: 'tr' },
      { label: 'Завершённые проекты', value: 'wealth' },
      { label: 'Распродажа', value: 'discount' },
      { label: 'Только онгоинги', value: 'ongoings' },
      { label: 'Убрать машинный', value: 'remove_machinelate' },
    ],
    inputType: FilterInputs.Checkbox,
  },
  {
    key: 'genres',
    label: 'Жанры',
    values: [
      { label: 'арт', value: '1' },
      { label: 'боевик', value: '2' },
      { label: 'боевые искусства', value: '3' },
      { label: 'вампиры', value: '4' },
      { label: 'гарем', value: '5' },
      { label: 'гендерная интрига', value: '6' },
      { label: 'героическое фэнтези', value: '7' },
      { label: 'детектив', value: '8' },
      { label: 'дзёсэй', value: '9' },
      { label: 'додзинси', value: '10' },
      { label: 'драма', value: '11' },
      { label: 'игра', value: '12' },
      { label: 'история', value: '13' },
      { label: 'киберпанк', value: '46' },
      { label: 'кодомо', value: '14' },
      { label: 'комедия', value: '15' },
      { label: 'литрпг', value: '48' },
      { label: 'махо-сёдзё', value: '16' },
      { label: 'мелодрама', value: '49' },
      { label: 'меха', value: '17' },
      { label: 'мистика', value: '18' },
      { label: 'научная фантастика', value: '19' },
      { label: 'повседневность', value: '20' },
      { label: 'постапокалиптика', value: '21' },
      { label: 'приключения', value: '22' },
      { label: 'психология', value: '23' },
      { label: 'романтика', value: '24' },
      { label: 'самурайский боевик', value: '25' },
      { label: 'сверхъестественное', value: '26' },
      { label: 'сёдзё', value: '27' },
      { label: 'сёдзё-ай', value: '28' },
      { label: 'сёнэн', value: '29' },
      { label: 'сёнэн-ай', value: '30' },
      { label: 'смат', value: '45' },
      { label: 'спорт', value: '31' },
      { label: 'сэйнэн', value: '32' },
      { label: 'сюаньхуа', value: '44' },
      { label: 'сюаньхуань', value: '47' },
      { label: 'сянься (XianXia)', value: '42' },
      { label: 'трагедия', value: '33' },
      { label: 'триллер', value: '34' },
      { label: 'ужасы', value: '35' },
      { label: 'уся (wuxia)', value: '41' },
      { label: 'фантастика', value: '36' },
      { label: 'фанфик', value: '50' },
      { label: 'фэнтези', value: '37' },
      { label: 'школа', value: '38' },
      { label: 'этти', value: '39' },
      { label: 'юри', value: '40' },
      { label: 'яой', value: '43' },
    ],
    inputType: FilterInputs.Checkbox,
  },
  {
    key: 'tags',
    label: 'Тэги',
    values: [
      { label: 'ад', value: '2623' },
      { label: 'ад и рай', value: '817' },
      { label: 'азгард', value: '3494' },
      { label: 'академия', value: '316' },
      { label: 'америка', value: '4082' },
      { label: 'асгард', value: '3635' },
      { label: 'бездна', value: '1026' },
      { label: 'библиотека', value: '4210' },
      { label: 'боевая академия', value: '2108' },
      { label: 'виртуальная реальность', value: '325' },
      { label: 'волшебный мир', value: '1623' },
      { label: 'гильдия авантюристов', value: '1858' },
      { label: 'голливуд', value: '7754' },
      { label: 'гробница', value: '388' },
      { label: 'добрый мир', value: '1685' },
      { label: 'древний египет', value: '7614' },
      { label: 'древний китай', value: '473' },
      { label: 'древний мир', value: '4' },
      { label: 'другая вселенная', value: '39' },
      { label: 'другие планеты', value: '2371' },
      { label: 'другой мир', value: '2248' },
      { label: 'европейская атмосфера', value: '5837' },
      { label: 'египет', value: '528' },
      { label: 'земля', value: '82' },
      { label: 'зона 51', value: '3051' },
      { label: 'империя', value: '1716' },
      { label: 'каракура', value: '7473' },
      { label: 'кафе', value: '3934' },
      { label: 'китай', value: '3762' },
      { label: 'колледж', value: '5058' },
      { label: 'коноха', value: '2827' },
      { label: 'корея', value: '2443' },
      { label: 'королевство', value: '1695' },
      { label: 'космос', value: '329' },
      { label: 'лес', value: '6645' },
      { label: 'лориен', value: '7397' },
      { label: 'магазин', value: '4762' },
      { label: 'магическая академия', value: '6788' },
      { label: 'магический мир', value: '578' },
      { label: 'марс', value: '4013' },
      { label: 'мегаполис', value: '3322' },
      { label: 'море', value: '922' },
      { label: 'мультивселенная', value: '7410' },
      { label: 'назарик', value: '5369' },
      { label: 'начальная школа', value: '3920' },
      { label: 'отель', value: '2879' },
      { label: 'офис', value: '3460' },
      { label: 'пандорум', value: '4360' },
      { label: 'пляж', value: '4243' },
      { label: 'подземелье', value: '798' },
      { label: 'преступный мир', value: '965' },
      { label: 'психбольница', value: '6969' },
      { label: 'путешествие во времени', value: '1549' },
      { label: 'ресторан', value: '7519' },
      { label: 'рим', value: '612' },
      { label: 'российская империя', value: '2146' },
      { label: 'россия', value: '4246' },
      { label: 'русь', value: '2016' },
      { label: 'средневековье', value: '1022' },
      { label: 'старшая школа', value: '1658' },
      { label: 'токио', value: '5791' },
      { label: 'трактир', value: '1918' },
      { label: 'тюрьма', value: '5597' },
      { label: 'университет', value: '2102' },
      { label: 'учеба в университете', value: '2797' },
      { label: 'учебное заведение', value: '1817' },
      { label: 'ферма', value: '285' },
      { label: 'филиппины', value: '128' },
      { label: 'хогвартс', value: '5954' },
      { label: 'храм', value: '2135' },
      { label: 'школа', value: '169' },
      { label: 'япония', value: '4537' },
      { label: 'библия', value: '488' },
      { label: 'буддизм', value: '1871' },
      { label: 'даосизм', value: '258' },
      { label: 'кланы', value: '834' },
      { label: 'коммунисты', value: '1042' },
      { label: 'матриархат', value: '7197' },
      { label: 'монархия', value: '3590' },
      { label: 'национализм', value: '5556' },
      { label: 'религия', value: '2184' },
      { label: 'ритуал', value: '1233' },
      { label: 'секты', value: '1234' },
      { label: 'феминизм', value: '6527' },
      { label: 'феодализм', value: '280' },
      { label: 'хаос', value: '3117' },
      { label: 'христианство', value: '877' },
      { label: 'церковь', value: '1980' },
      { label: 'эзотерика', value: '2713' },
      { label: 'tower defense', value: '3682' },
      { label: 'video game', value: '3038' },
      { label: 'авторский мир', value: '1062' },
      { label: 'адаптация произведения', value: '192' },
      { label: 'азартные игры', value: '5301' },
      { label: 'альтернативное развитие событий', value: '5330' },
      { label: 'амнезия', value: '2207' },
      { label: 'андрогинные персонажи', value: '2335' },
      { label: 'аниме', value: '1294' },
      { label: 'аристократия', value: '371' },
      { label: 'археология', value: '6523' },
      { label: 'басейн', value: '6847' },
      { label: 'бедность', value: '1207' },
      { label: 'без культивации', value: '668' },
      { label: 'без любовной линий', value: '2225' },
      { label: 'без перерождений', value: '262' },
      { label: 'без системы', value: '747' },
      { label: 'безумие', value: '37' },
      { label: 'без юмора', value: '763' },
      { label: 'беременность', value: '2122' },
      { label: 'бизнес', value: '704' },
      { label: 'биология', value: '2220' },
      { label: 'битва за веру', value: '721' },
      { label: 'битва за трон', value: '7211' },
      { label: 'битва королевств', value: '1151' },
      { label: 'битва рас', value: '6989' },
      { label: 'битвы', value: '1740' },
      { label: 'богатство', value: '6522' },
      { label: 'богохульство', value: '95' },
      { label: 'боевые искусства', value: '2090' },
      { label: 'борьба', value: '1925' },
      { label: 'брак', value: '1558' },
      { label: 'брак по расчету', value: '1389' },
      { label: 'братский комплекс', value: '2321' },
      { label: 'брошенные дети', value: '2846' },
      { label: 'будущее', value: '1820' },
      { label: 'быстрое развитие', value: '1443' },
      { label: 'взросление', value: '624' },
      { label: 'видео игры', value: '2630' },
      { label: 'возвращение во времени', value: '1632' },
      { label: 'возрождение', value: '1160' },
      { label: 'война', value: '443' },
      { label: 'волшебство', value: '719' },
      { label: 'воспоминания из другого мира', value: '1366' },
      { label: 'воспоминания из прошлого', value: '1372' },
      { label: 'восхождение', value: '380' },
      { label: 'враги становятся любовниками', value: '978' },
      { label: 'временная петля', value: '2852' },
      { label: 'вторжение пришельцев', value: '346' },
      { label: 'второй шанс', value: '2372' },
      { label: 'вынужденный брак', value: '7705' },
      { label: 'высокие технологии', value: '653' },
      { label: 'в этот же мир', value: '49' },
      { label: 'гендерная интрига', value: '773' },
      { label: 'династии', value: '2982' },
      { label: 'договоры с богами', value: '2152' },
      { label: 'договоры с демонами', value: '1922' },
      { label: 'древние времена', value: '7781' },
      { label: 'дружба', value: '1903' },
      { label: 'друзья детства', value: '1153' },
      { label: 'женщина в теле мужчины', value: '2748' },
      { label: 'жестокий мир', value: '1532' },
      { label: 'жизнь и смерть', value: '2014' },
      { label: 'завоевание мира', value: '1319' },
      { label: 'закалка тела', value: '148' },
      { label: 'запутанный сюжет', value: '1041' },
      { label: 'захват мира', value: '315' },
      { label: 'игра', value: '663' },
      { label: 'игра на выживание', value: '2182' },
      { label: 'игровая система', value: '384' },
      { label: 'измена', value: '1874' },
      { label: 'изменения внешности', value: '259' },
      { label: 'изменения личности', value: '1080' },
      { label: 'инопланетное вторжение', value: '209' },
      { label: 'интерактив с читателями', value: '472' },
      { label: 'интересный сюжет', value: '7374' },
      { label: 'интимные сцены', value: '3450' },
      { label: 'интриги и заговоры', value: '1009' },
      { label: 'иные миры', value: '35' },
      { label: 'исследование', value: '1626' },
      { label: 'квесты', value: '1707' },
      { label: 'контроль разума', value: '485' },
      { label: 'красивые женщины', value: '66' },
      { label: 'красивые персонажи ', value: '5787' },
      { label: 'кулинария', value: '2230' },
      { label: 'культивирование', value: '1860' },
      { label: 'лавкрафт', value: '6063' },
      { label: 'любовный треугольник', value: '2109' },
      { label: 'любовь', value: '2297' },
      { label: 'любовь с первого взгляда', value: '7748' },
      { label: 'любящие родители', value: '2699' },
      { label: 'магия и технология', value: '107' },
      { label: 'манга', value: '2464' },
      { label: 'медицина', value: '441' },
      { label: 'медленное развитие истории', value: '7462' },
      { label: 'менеджмент', value: '368' },
      { label: 'месть', value: '1218' },
      { label: 'мир будущего', value: '1770' },
      { label: 'мир меча и магии', value: '1271' },
      { label: 'мифы и легенды', value: '4463' },
      { label: 'много главных героев', value: '1191' },
      { label: 'много персонажей', value: '1539' },
      { label: 'множество королевств', value: '32' },
      { label: 'мрачный мир', value: '1' },
      { label: 'мужская беременность', value: '1043' },
      { label: 'мужчина протагонист', value: '31' },
      { label: 'на реальных событиях', value: '26' },
      { label: 'наука', value: '2150' },
      { label: 'наши дни', value: '1814' },
      { label: 'необычные герои', value: '67' },
      { label: 'не по канону', value: '1611' },
      { label: 'обратный гарем', value: '3303' },
      { label: 'одержимость', value: '708' },
      { label: 'один в поле воин', value: '6498' },
      { label: 'онлайн игра', value: '1565' },
      { label: 'основано на видео игре', value: '602' },
      { label: 'от бедности к богатству', value: '901' },
      { label: 'отношения человек/нечеловек', value: '7406' },
      { label: 'от слабого до сильного', value: '118' },
      { label: 'параллельный мир', value: '2092' },
      { label: 'пасхалки', value: '455' },
      { label: 'первая любовь', value: '640' },
      { label: 'перевоплощение', value: '1596' },
      { label: 'перевоплощение в игровом мире', value: '92' },
      { label: 'перемещение в другой мир', value: '1288' },
      { label: 'перемещение во времени', value: '146' },
      { label: 'перерождение', value: '894' },
      { label: 'перерождение в демона', value: '1111' },
      { label: 'перерождение в дракона', value: '6867' },
      { label: 'перерождение в другом мире', value: '1574' },
      { label: 'перерождение в злодейку', value: '5619' },
      { label: 'перерождение в злодея', value: '749' },
      { label: 'перерождение в ином мире', value: '109' },
      { label: 'перерождение в монстра', value: '917' },
      { label: 'перерождений', value: '335' },
      { label: 'переселение', value: '813' },
      { label: 'переселение души', value: '1864' },
      { label: 'планомерное развитие событий', value: '62' },
      { label: 'повествование от первого лица', value: '1054' },
      { label: 'повествование от разных лиц', value: '600' },
      { label: 'повествование от третьего лица', value: '2116' },
      { label: 'политика', value: '1313' },
      { label: 'попаданец в другой мир', value: '685' },
      { label: 'попаданец в игру', value: '6466' },
      { label: 'попадание в книгу', value: '6957' },
      { label: 'потеря памяти', value: '245' },
      { label: 'похищение', value: '7452' },
      { label: 'преданный любовный интерес', value: '2055' },
      { label: 'предательство', value: '70' },
      { label: 'приготовление пищи', value: '3073' },
      { label: 'призыв в другой мир', value: '781' },
      { label: 'принудительный брак', value: '2954' },
      { label: 'прокачка', value: '1070' },
      { label: 'путешествие в другой мир', value: '10' },
      { label: 'пушечное мясо', value: '7234' },
      { label: 'развитие технологий', value: '1875' },
      { label: 'раздвоение личности', value: '2062' },
      { label: 'ранги', value: '1568' },
      { label: 'реанкарнация', value: '206' },
      { label: 'революция', value: '3996' },
      { label: 'реинкарнация', value: '1302' },
      { label: 'реинкарнация в другом мире', value: '2180' },
      { label: 'реинкарнация в игровой мир', value: '304' },
      { label: 'ремонт', value: '5703' },
      { label: 'сарказм', value: '4658' },
      { label: 'свадьба', value: '1524' },
      { label: 'сельское хозяйство', value: '787' },
      { label: 'семейный конфликт', value: '935' },
      { label: 'сильная героиня', value: '7292' },
      { label: 'система уровней', value: '2174' },
      { label: 'смена пола', value: '2142' },
      { label: 'смерть основного персонажа', value: '1530' },
      { label: 'современность', value: '568' },
      { label: 'сожительство', value: '3026' },
      { label: 'создание армии', value: '1992' },
      { label: 'сокрытие истинной личности', value: '2894' },
      { label: 'соперничество', value: '7699' },
      { label: 'сражения', value: '23' },
      { label: 'становление государства', value: '111' },
      { label: 'стеснительный персонаж', value: '152' },
      { label: 'стёб', value: '454' },
      { label: 'стратегия', value: '569' },
      { label: 'строительство', value: '921' },
      { label: 'схемы и заговоры', value: '7116' },
      { label: 'счастливый конец', value: '3293' },
      { label: 'сюжетные повороты', value: '7202' },
      { label: 'таинственное прошлое', value: '769' },
      { label: 'тайная любовь', value: '113' },
      { label: 'тайные отношения', value: '7450' },
      { label: 'технология и магия', value: '929' },
      { label: 'трагическое прошлое', value: '644' },
      { label: 'тяжёлое детство', value: '2253' },
      { label: 'убийства', value: '378' },
      { label: 'умные персонажи', value: '2756' },
      { label: 'уничтожение мира', value: '81' },
      { label: 'уровни', value: '8' },
      { label: 'устроенный брак', value: '2223' },
      { label: 'усыновление', value: '395' },
      { label: 'фанатичная любовь', value: '6721' },
      { label: 'фантастический мир', value: '2414' },
      { label: 'фэнтезийный мир', value: '1556' },
      { label: 'читер', value: '1049' },
      { label: 'шантаж', value: '7175' },
      { label: 'школьная жизнь', value: '284' },
      { label: 'шоу-бизнес', value: '7119' },
      { label: 'эволюция', value: '2040' },
      { label: 'экспансия', value: '110' },
      { label: 'эксперименты над людьми', value: '7408' },
      { label: 'юмор', value: '7360' },
      { label: 'автомат', value: '5272' },
      { label: 'аквакинез', value: '5952' },
      { label: 'антиквариат', value: '3552' },
      { label: 'артефакты', value: '2296' },
      { label: 'аугментации', value: '7751' },
      { label: 'бесконечный поток', value: '7556' },
      { label: 'веб камера', value: '5664' },
      { label: 'вино', value: '6972' },
      { label: 'власть', value: '756' },
      { label: 'воскрешение', value: '6915' },
      { label: 'генетические модификации', value: '1750' },
      { label: 'гений', value: '1650' },
      { label: 'гипноз', value: '358' },
      { label: 'дневник', value: '298' },
      { label: 'доудзюцу', value: '7133' },
      { label: 'духовные силы', value: '1955' },
      { label: 'дьявольские фрукты', value: '1564' },
      { label: 'еда', value: '2056' },
      { label: 'заклинания', value: '558' },
      { label: 'занпакто', value: '1102' },
      { label: 'знание медицины', value: '1411' },
      { label: 'изобретения', value: '126' },
      { label: 'интернет', value: '739' },
      { label: 'камень', value: '1807' },
      { label: 'книги', value: '1068' },
      { label: 'колдовство', value: '2681' },
      { label: 'кольцо', value: '1628' },
      { label: 'контракт', value: '4304' },
      { label: 'конфеты', value: '341' },
      { label: 'королевская власть', value: '55' },
      { label: 'кража навыков', value: '1159' },
      { label: 'крафт', value: '1599' },
      { label: 'кукла', value: '3085' },
      { label: 'куклы', value: '7479' },
      { label: 'лечебная магия', value: '562' },
      { label: 'лопата', value: '4989' },
      { label: 'лунатизм', value: '3520' },
      { label: 'маги', value: '58' },
      { label: 'магические предметы', value: '1648' },
      { label: 'магия', value: '150' },
      { label: 'магия воды', value: '6450' },
      { label: 'магия воздуха', value: '7627' },
      { label: 'магия земли', value: '7626' },
      { label: 'магия льда', value: '1379' },
      { label: 'магия огня', value: '7625' },
      { label: 'магия призыва', value: '885' },
      { label: 'магия природы', value: '6226' },
      { label: 'магия стихий', value: '7673' },
      { label: 'магия тьмы', value: '3596' },
      { label: 'манипуляция временем', value: '932' },
      { label: 'марионетки', value: '3175' },
      { label: 'мастер на все руки', value: '3189' },
      { label: 'меч', value: '48' },
      { label: 'мозги', value: '7649' },
      { label: 'мокутон', value: '4438' },
      { label: 'молоко', value: '5469' },
      { label: 'мурим', value: '7342' },
      { label: 'мутация', value: '29' },
      { label: 'мясо', value: '1503' },
      { label: 'некромантия', value: '754' },
      { label: 'ниндзюцу', value: '2354' },
      { label: 'овощ', value: '6098' },
      { label: 'огнестрельное оружие', value: '3155' },
      { label: 'оружие', value: '125' },
      { label: 'особые способности', value: '2904' },
      { label: 'остановка времени', value: '6776' },
      { label: 'ошейник', value: '2362' },
      { label: 'палочка', value: '2682' },
      { label: 'паркур', value: '3391' },
      { label: 'пилюли', value: '1531' },
      { label: 'пирог', value: '80' },
      { label: 'пистолеты', value: '4916' },
      { label: 'письмо', value: '840' },
      { label: 'плети', value: '4839' },
      { label: 'поношенные трусики', value: '1204' },
      { label: 'превращения в животных', value: '3410' },
      { label: 'призыв', value: '332' },
      { label: 'призыв существ', value: '412' },
      { label: 'приложение на телефоне', value: '5345' },
      { label: 'приручение мостров', value: '2338' },
      { label: 'проклятия', value: '1347' },
      { label: 'пророчество', value: '7762' },
      { label: 'псионика', value: '5216' },
      { label: 'пух', value: '4286' },
      { label: 'пьяный мастер', value: '1655' },
      { label: 'раб', value: '977' },
      { label: 'разведение животных', value: '3990' },
      { label: 'растение', value: '407' },
      { label: 'риннеган', value: '4230' },
      { label: 'роботы', value: '467' },
      { label: 'руны', value: '2393' },
      { label: 'сабли', value: '6136' },
      { label: 'сверхсила', value: '1055' },
      { label: 'свинцовые книги', value: '5322' },
      { label: 'сила глаза', value: '1019' },
      { label: 'сила души', value: '1254' },
      { label: 'скрытые способности', value: '3417' },
      { label: 'смартфон', value: '457' },
      { label: 'соблазнение', value: '2290' },
      { label: 'современные знания', value: '988' },
      { label: 'создание пилюль', value: '816' },
      { label: 'сокровища', value: '6521' },
      { label: 'способность кражи', value: '7784' },
      { label: 'стекло', value: '7453' },
      { label: 'стиль льда', value: '1603' },
      { label: 'супер зрение', value: '6574' },
      { label: 'суперсилы', value: '2276' },
      { label: 'супер удача', value: '489' },
      { label: 'сферы', value: '1077' },
      { label: 'схемы', value: '348' },
      { label: 'таблетки для развития', value: '589' },
      { label: 'танки', value: '1787' },
      { label: 'телекинез', value: '2203' },
      { label: 'телепортация', value: '914' },
      { label: 'темная магия', value: '4788' },
      { label: 'тенсейган', value: '4367' },
      { label: 'техномагия', value: '508' },
      { label: 'травничество', value: '221' },
      { label: 'трансформация', value: '156' },
      { label: 'увечья', value: '3266' },
      { label: 'удача', value: '6575' },
      { label: 'укротитель', value: '367' },
      { label: 'умный', value: '1229' },
      { label: 'управление временем', value: '5648' },
      { label: 'усиление', value: '3549' },
      { label: 'холодное оружие', value: '4889' },
      { label: 'цветок', value: '902' },
      { label: 'читы', value: '451' },
      { label: 'шаринган', value: '5165' },
      { label: 'шизофрения', value: '5344' },
      { label: 'щит', value: '7442' },
      { label: 'щупальца', value: '5194' },
      { label: 'эволюционирующее оружие', value: '1890' },
      { label: 'экзорцизм', value: '676' },
      { label: 'экзоскелет', value: '1521' },
      { label: 'элементальная магия', value: '1264' },
      { label: 'эликсиры', value: '1594' },
      { label: 'яды', value: '201' },
      { label: 'rpg', value: '90' },
      { label: 'rts', value: '1252' },
      { label: 'ведьмак', value: '843' },
      { label: 'врмморпг', value: '2043' },
      { label: 'дарк соулс', value: '6057' },
      { label: 'дота', value: '6965' },
      { label: 'игровые элементы', value: '720' },
      { label: 'карточная игра', value: '1557' },
      { label: 'космические рейнджеры', value: '5860' },
      { label: 'легенда о зельде', value: '5707' },
      { label: 'мморпг', value: '620' },
      { label: 'мортал комбат', value: '5861' },
      { label: 'скайрим', value: '4032' },
      { label: 'time skip', value: '824' },
      { label: 'xuanhuan', value: '785' },
      { label: 'алхимия', value: '1473' },
      { label: 'ангст', value: '4638' },
      { label: 'анимализм', value: '5249' },
      { label: 'антиутопия', value: '662' },
      { label: 'апокалипсис', value: '1498' },
      { label: 'биседзе', value: '777' },
      { label: 'боевик', value: '529' },
      { label: 'бояръ', value: '2307' },
      { label: 'броманс', value: '1103' },
      { label: 'веб новелла', value: '2349' },
      { label: 'вестерн', value: '2131' },
      { label: 'выживание', value: '501' },
      { label: 'героическое фэнтези', value: '1148' },
      { label: 'головоломка', value: '1697' },
      { label: 'гуро', value: '1510' },
      { label: 'даньмэй', value: '3411' },
      { label: 'детектив', value: '1265' },
      { label: 'дзесэй', value: '678' },
      { label: 'драма', value: '611' },
      { label: 'зомби апокалипсис', value: '912' },
      { label: 'интрига', value: '317' },
      { label: 'исекай', value: '2979' },
      { label: 'исторический роман', value: '573' },
      { label: 'киберпанк', value: '1614' },
      { label: 'комедия', value: '1430' },
      { label: 'космическая опера', value: '2245' },
      { label: 'кроссовер', value: '75' },
      { label: 'культивация', value: '1901' },
      { label: 'литрпг', value: '505' },
      { label: 'марти стью', value: '594' },
      { label: 'мелодрама', value: '1507' },
      { label: 'меха', value: '2303' },
      { label: 'мистика', value: '510' },
      { label: 'модерн', value: '5457' },
      { label: 'научная фантастика', value: '2244' },
      { label: 'нетораре', value: '403' },
      { label: 'новелла', value: '2105' },
      { label: 'пародия', value: '898' },
      { label: 'повседневность', value: '802' },
      { label: 'попаданец', value: '2396' },
      { label: 'постапокалипсис', value: '1079' },
      { label: 'поэзия', value: '1120' },
      { label: 'приключения', value: '964' },
      { label: 'проза', value: '2012' },
      { label: 'психология', value: '17' },
      { label: 'ранобэ', value: '1764' },
      { label: 'реализм', value: '1180' },
      { label: 'романтика', value: '1025' },
      { label: 'сатира', value: '215' },
      { label: 'сёдзе', value: '2219' },
      { label: 'сёнэн', value: '2058' },
      { label: 'сёнэн-ай', value: '7643' },
      { label: 'система', value: '251' },
      { label: 'сказка', value: '3570' },
      { label: 'слэш', value: '4417' },
      { label: 'стимпанк', value: '1894' },
      { label: 'стихи', value: '1309' },
      { label: 'сэйнэн', value: '345' },
      { label: 'сюаньхуа', value: '2560' },
      { label: 'сянься', value: '1126' },
      { label: 'темное фэнтези', value: '1675' },
      { label: 'трагедия', value: '470' },
      { label: 'триллер', value: '1676' },
      { label: 'ужасы', value: '1747' },
      { label: 'уся', value: '1172' },
      { label: 'утопия', value: '4677' },
      { label: 'фантастика', value: '286' },
      { label: 'фанфик', value: '767' },
      { label: 'философия', value: '1859' },
      { label: 'флафф', value: '5048' },
      { label: 'фольклор', value: '4086' },
      { label: 'фурри', value: '6631' },
      { label: 'футанари', value: '1996' },
      { label: 'фэнтези', value: '174' },
      { label: 'художественная литература', value: '2380' },
      { label: 'цундере', value: '1078' },
      { label: 'черный юмор', value: '2868' },
      { label: 'экшен', value: '2859' },
      { label: 'этти', value: '1317' },
      { label: 'юри', value: '1799' },
      { label: 'яндере', value: '7111' },
      { label: 'яой', value: '1224' },
      { label: 'online', value: '803' },
      { label: 'star wars', value: '1985' },
      { label: 'актерское мастерство', value: '4798' },
      { label: 'аллегория', value: '271' },
      { label: 'алчность', value: '6897' },
      { label: 'альянсы', value: '328' },
      { label: 'армия', value: '1723' },
      { label: 'безработный', value: '2202' },
      { label: 'бейсбол', value: '7623' },
      { label: 'влюбленность', value: '6132' },
      { label: 'внешний вид отличается от личности', value: '1938' },
      { label: 'волейбол', value: '6415' },
      { label: 'врата', value: '40' },
      { label: 'врата в другой мир', value: '1957' },
      { label: 'все дозволено', value: '96' },
      { label: 'герои', value: '185' },
      { label: 'гильдии', value: '900' },
      { label: 'готовка', value: '1104' },
      { label: 'действие', value: '1425' },
      { label: 'демонология', value: '2024' },
      { label: 'для девушек', value: '1441' },
      { label: 'животные компаньоны', value: '2061' },
      { label: 'забота о детях', value: '7478' },
      { label: 'завершено', value: '5415' },
      { label: 'зачарованные', value: '4169' },
      { label: 'звери', value: '1638' },
      { label: 'злая организация', value: '7768' },
      { label: 'зло', value: '1512' },
      { label: 'злодей', value: '1060' },
      { label: 'злодейка', value: '2376' },
      { label: 'зрелые женщины', value: '1458' },
      { label: 'изменение характера', value: '1113' },
      { label: 'имба', value: '137' },
      { label: 'империи', value: '712' },
      { label: 'инвалидность', value: '2073' },
      { label: 'искусственный интеллект', value: '1900' },
      { label: 'киберспорт', value: '1984' },
      { label: 'кино', value: '7126' },
      { label: 'королевская семья', value: '276' },
      { label: 'короткий рассказ', value: '239' },
      { label: 'коррупция', value: '831' },
      { label: 'лгбт', value: '3136' },
      { label: 'любовный интерес влюбляется первым', value: '7753' },
      { label: 'мафия', value: '353' },
      { label: 'мечта', value: '527' },
      { label: 'музыка', value: '1183' },
      { label: 'навыки', value: '415' },
      { label: 'нет людей', value: '7486' },
      { label: 'отношения', value: '398' },
      { label: 'первая книга', value: '269' },
      { label: 'переводы', value: '24' },
      { label: 'подавитель', value: '497' },
      { label: 'полиамория', value: '1300' },
      { label: 'полигамия', value: '1336' },
      { label: 'полукровка', value: '999' },
      { label: 'проработанный мир', value: '1711' },
      { label: 'психические расстройства', value: '2445' },
      { label: 'психологические травмы', value: '3418' },
      { label: 'развитие', value: '208' },
      { label: 'развитие персонажа', value: '1780' },
      { label: 'развитие поселения', value: '7203' },
      { label: 'разные расы', value: '1188' },
      { label: 'разорванная помолвка', value: '2057' },
      { label: 'расизм', value: '3554' },
      { label: 'ревность', value: '293' },
      { label: 'сборник', value: '7367' },
      { label: 'сверхъестественное', value: '1074' },
      { label: 'своё королевство', value: '189' },
      { label: 'слизерин', value: '6979' },
      { label: 'смерть', value: '1779' },
      { label: 'создание королевства', value: '1497' },
      { label: 'социология', value: '7618' },
      { label: 'спор', value: '3484' },
      { label: 'спорт', value: '1387' },
      { label: 'сценарий', value: '7489' },
      { label: 'тайны', value: '7481' },
      { label: 'творчество', value: '20' },
      { label: 'торговля', value: '1637' },
      { label: 'трансмиграция', value: '1071' },
      { label: 'умения', value: '531' },
      { label: 'уход за детьми', value: '7609' },
      { label: 'футбол', value: '1121' },
      { label: 'чакра', value: '1393' },
      { label: 'шаблон', value: '814' },
      { label: 'экономика', value: '121' },
      { label: 'mahouka', value: '1631' },
      { label: 'peter and mj', value: '3804' },
      { label: 'shogun', value: '2614' },
      { label: 'warrior of light', value: '5289' },
      { label: 'авантюристы', value: '222' },
      { label: 'агрессивные персонажи', value: '3249' },
      { label: 'адам дженсен', value: '1649' },
      { label: 'адвокат', value: '6340' },
      { label: 'адекватные главные герои', value: '1953' },
      { label: 'азула', value: '5550' },
      { label: 'аид', value: '7641' },
      { label: 'айдолы', value: '4081' },
      { label: 'акамэ', value: '5059' },
      { label: 'акира', value: '2639' },
      { label: 'акнология', value: '4634' },
      { label: 'актёры', value: '7506' },
      { label: 'активные герои', value: '6376' },
      { label: 'акутагава рюноске', value: '4113' },
      { label: 'аладдин', value: '6489' },
      { label: 'алая ведьма', value: '4767' },
      { label: 'алиса', value: '4761' },
      { label: 'алукард', value: '4914' },
      { label: 'алхимики', value: '1164' },
      { label: 'альбус дамблдор', value: '5784' },
      { label: 'амбициозный главный герой', value: '3751' },
      { label: 'аморальный герой', value: '18' },
      { label: 'ангелы', value: '857' },
      { label: 'ангелы и демоны', value: '1327' },
      { label: 'андроиды', value: '1993' },
      { label: 'анко митараши', value: '5768' },
      { label: 'антагонист', value: '2144' },
      { label: 'антигерой', value: '7725' },
      { label: 'антимаг', value: '1348' },
      { label: 'аристократы', value: '7338' },
      { label: 'артас', value: '6700' },
      { label: 'ассасин', value: '1415' },
      { label: 'асуна', value: '5044' },
      { label: 'ацуши накаджима', value: '4109' },
      { label: 'аянокоджи киетака', value: '6862' },
      { label: 'бандиты', value: '2188' },
      { label: 'бастарды', value: '76' },
      { label: 'безжалостное домашнее животное', value: '1245' },
      { label: 'безжалостные персонажи', value: '2986' },
      { label: 'беззаботные персонажи ', value: '3123' },
      { label: 'безумные персонажи', value: '2049' },
      { label: 'беспечные персонажи', value: '742' },
      { label: 'бессмертные персонажи', value: '566' },
      { label: 'бесстрашные персонажи', value: '6921' },
      { label: 'бесстыдные персонажи', value: '1257' },
      { label: 'биомехи', value: '1968' },
      { label: 'благородные персонажи', value: '2201' },
      { label: 'близнецы', value: '2931' },
      { label: 'богатые персонажи', value: '520' },
      { label: 'боги', value: '173' },
      { label: 'богини', value: '30' },
      { label: 'богоубийца', value: '1253' },
      { label: 'борос', value: '6533' },
      { label: 'босс и подчиненный', value: '7157' },
      { label: 'брат и сестра', value: '615' },
      { label: 'бэтгерл', value: '2584' },
      { label: 'бэтмен', value: '4668' },
      { label: 'валькирии', value: '4047' },
      { label: 'вампиры', value: '2206' },
      { label: 'ведьмы', value: '643' },
      { label: 'везучие персонажи', value: '1879' },
      { label: 'веном', value: '3994' },
      { label: 'взрослый главный герой', value: '2416' },
      { label: 'викинги', value: '267' },
      { label: 'вирусы', value: '3327' },
      { label: 'владыка демонов', value: '555' },
      { label: 'военные', value: '1096' },
      { label: 'воины', value: '287' },
      { label: 'войны', value: '2431' },
      { label: 'воландеморт', value: '4278' },
      { label: 'волки', value: '1166' },
      { label: 'волшебники', value: '122' },
      { label: 'волшебные существа', value: '1689' },
      { label: 'вор', value: '1399' },
      { label: 'воровка', value: '6948' },
      { label: 'ворон', value: '848' },
      { label: 'врач', value: '1243' },
      { label: 'всемогущий главный герой', value: '1414' },
      { label: 'вымышленные существа', value: '3466' },
      { label: 'высокомерные персонажи', value: '3250' },
      { label: 'галустян', value: '5199' },
      { label: 'гангстеры', value: '7704' },
      { label: 'гарри поттер', value: '226' },
      { label: 'геймеры', value: '2130' },
      { label: 'гениальный главный герой', value: '1500' },
      { label: 'гермиона грейнджер', value: '4280' },
      { label: 'гильгамеш', value: '6031' },
      { label: 'гинтама', value: '4544' },
      { label: 'главная героиня влюбляется первой', value: '973' },
      { label: 'главный герой бог', value: '164' },
      { label: 'главный герой влюбляется первым', value: '3629' },
      { label: 'главный герой выживальщик', value: '120' },
      { label: 'главный герой девушка', value: '257' },
      { label: 'главный герой демон', value: '136' },
      { label: 'главный герой женщина', value: '7329' },
      { label: 'главный герой жестокий', value: '1553' },
      { label: 'главный герой извращенец', value: '94' },
      { label: 'главный герой имба', value: '2421' },
      { label: 'главный герой киборг', value: '7780' },
      { label: 'главный герой монстр', value: '869' },
      { label: 'главный герой мужчина', value: '1997' },
      { label: 'главный герой на стороне сил зла', value: '1514' },
      { label: 'главный герой не адекватный', value: '5' },
      { label: 'главный герой не психопат', value: '7804' },
      { label: 'главный герой не человек', value: '2172' },
      { label: 'главный герой не эмоционален', value: '1150' },
      { label: 'главный герой подросток', value: '2215' },
      { label: 'главный герой позитивный', value: '7787' },
      { label: 'главный герой психопат', value: '7803' },
      { label: 'главный герой ребенок', value: '2347' },
      { label: 'главный герой русский', value: '2417' },
      { label: 'главный герой сильный с самого начала', value: '88' },
      { label: 'главный герой скрывает свою силу', value: '1059' },
      { label: 'гномы', value: '1870' },
      { label: 'гоблины', value: '2029' },
      { label: 'годзилла', value: '6990' },
      { label: 'големы', value: '1690' },
      { label: 'дазай осаму', value: '4112' },
      { label: 'дарт вейдер', value: '6826' },
      { label: 'дафна гринграсс', value: '5192' },
      { label: 'дворяне', value: '7204' },
      { label: 'девушки', value: '7668' },
      { label: 'девушки монстры', value: '2231' },
      { label: 'демон лорд', value: '153' },
      { label: 'демоны', value: '1406' },
      { label: 'демоны и ангелы', value: '1211' },
      { label: 'дети', value: '580' },
      { label: 'джарвис', value: '933' },
      { label: 'джедай', value: '4442' },
      { label: 'джин', value: '4024' },
      { label: 'джокер', value: '3351' },
      { label: 'джон сноу', value: '7412' },
      { label: 'джоффри баратеон', value: '3936' },
      { label: 'джулиан', value: '6052' },
      { label: 'дин винчестер', value: '6953' },
      { label: 'динозавры', value: '3666' },
      { label: 'директор', value: '1417' },
      { label: 'добби', value: '6762' },
      { label: 'доктор', value: '1991' },
      { label: 'доктор стрэндж', value: '7634' },
      { label: 'дочь', value: '3291' },
      { label: 'драко малфой', value: '46' },
      { label: 'драконы', value: '282' },
      { label: 'друг детства', value: '2361' },
      { label: 'духи', value: '114' },
      { label: 'души', value: '1212' },
      { label: 'дьявол', value: '1094' },
      { label: 'дэдпул', value: '4399' },
      { label: 'евнух', value: '6293' },
      { label: 'единороги', value: '437' },
      { label: 'екаи', value: '655' },
      { label: 'жалкий главный герой', value: '97' },
      { label: 'жена', value: '5729' },
      { label: 'женщина кошка', value: '7513' },
      { label: 'жестокие персонажи ', value: '3153' },
      { label: 'животные', value: '7488' },
      { label: 'жнец', value: '6288' },
      { label: 'жойен рид', value: '3926' },
      { label: 'заботливый главный герой', value: '338' },
      { label: 'заключенные', value: '3052' },
      { label: 'зверодевочки', value: '2006' },
      { label: 'зверолюди', value: '1018' },
      { label: 'злой главный герой', value: '616' },
      { label: 'злые боги', value: '7109' },
      { label: 'злые персонажи', value: '3243' },
      { label: 'змей', value: '5721' },
      { label: 'знаменитости', value: '1341' },
      { label: 'золушка', value: '2980' },
      { label: 'зомби', value: '1743' },
      { label: 'зооморфы', value: '375' },
      { label: 'зорро', value: '6736' },
      { label: 'изуку мидория', value: '6967' },
      { label: 'император', value: '867' },
      { label: 'инкуб', value: '3264' },
      { label: 'инопланетяне', value: '866' },
      { label: 'итачи учиха', value: '4556' },
      { label: 'ичиго', value: '7254' },
      { label: 'йода', value: '6829' },
      { label: 'йоруичи', value: '6755' },
      { label: 'капитан америка', value: '6301' },
      { label: 'кастиэль', value: '6954' },
      { label: 'кацуки бакуго', value: '7696' },
      { label: 'кицунэ', value: '241' },
      { label: 'клоны', value: '1624' },
      { label: 'книжный червь', value: '521' },
      { label: 'коллекционер', value: '2588' },
      { label: 'корейцы', value: '6535' },
      { label: 'кот', value: '5171' },
      { label: 'красивая главная героиня', value: '186' },
      { label: 'красивый главный герой', value: '895' },
      { label: 'ктулху', value: '920' },
      { label: 'кузнец', value: '853' },
      { label: 'курама', value: '5709' },
      { label: 'курилин', value: '6134' },
      { label: 'кушина узумаки', value: '5222' },
      { label: 'лара крофт', value: '6435' },
      { label: 'ленивый главный герой', value: '1516' },
      { label: 'леон золдик', value: '7469' },
      { label: 'локи', value: '1725' },
      { label: 'лоли', value: '1576' },
      { label: 'лошади', value: '6110' },
      { label: 'луффи', value: '274' },
      { label: 'лучник', value: '1038' },
      { label: 'люди', value: '3572' },
      { label: 'люцифер', value: '5883' },
      { label: 'маг', value: '780' },
      { label: 'магические звери', value: '684' },
      { label: 'мадара', value: '2929' },
      { label: 'мама', value: '12' },
      { label: 'маньяк', value: '2026' },
      { label: 'маргери тирелл', value: '3935' },
      { label: 'мастер', value: '1971' },
      { label: 'мачеха', value: '4664' },
      { label: 'медведь', value: '6963' },
      { label: 'мелиодас', value: '7224' },
      { label: 'мерлин', value: '3977' },
      { label: 'мечники', value: '969' },
      { label: 'мизуки', value: '4269' },
      { label: 'микото', value: '3862' },
      { label: 'милая главная героиня', value: '134' },
      { label: 'милый главный герой', value: '2678' },
      { label: 'мимик', value: '5706' },
      { label: 'мина ашидо', value: '7695' },
      { label: 'минато намикадзе', value: '5223' },
      { label: 'мистер пропер', value: '565' },
      { label: 'мифические существа', value: '1878' },
      { label: 'младшая сестра', value: '1523' },
      { label: 'монстры', value: '307' },
      { label: 'моритика ринносукэ', value: '1142' },
      { label: 'мошенник', value: '959' },
      { label: 'мутанты', value: '2392' },
      { label: 'нагато узумаки', value: '5221' },
      { label: 'наемники', value: '1668' },
      { label: 'наивный главный герой', value: '159' },
      { label: 'наложница', value: '4867' },
      { label: 'наноботы', value: '2332' },
      { label: 'наруто', value: '7177' },
      { label: 'наруто и хината', value: '5766' },
      { label: 'натсу', value: '7246' },
      { label: 'нацу', value: '5826' },
      { label: 'нацуки субару', value: '6656' },
      { label: 'невеста', value: '6011' },
      { label: 'не всесильный главный герой', value: '42' },
      { label: 'неджи хьюга', value: '3099' },
      { label: 'недооценённый главный герой', value: '43' },
      { label: 'нежить', value: '1949' },
      { label: 'некромаг', value: '7441' },
      { label: 'некромант', value: '1914' },
      { label: 'нетори', value: '5393' },
      { label: 'нефилимы', value: '7764' },
      { label: 'нечисть', value: '4559' },
      { label: 'ник фьюри', value: '6304' },
      { label: 'ниндзя', value: '1330' },
      { label: 'нэко', value: '147' },
      { label: 'оби ван кеноби', value: '6830' },
      { label: 'обито учиха', value: '2814' },
      { label: 'оборотни', value: '53' },
      { label: 'ооками теппей', value: '849' },
      { label: 'оригинальные персонажи', value: '7741' },
      { label: 'орки', value: '1597' },
      { label: 'отец', value: '3290' },
      { label: 'охотники', value: '2263' },
      { label: 'оцуцуки', value: '5101' },
      { label: 'падчерица', value: '7023' },
      { label: 'падший ангел', value: '184' },
      { label: 'палач', value: '852' },
      { label: 'папа и дочь', value: '7647' },
      { label: 'паразит', value: '1213' },
      { label: 'парень', value: '619' },
      { label: 'паук', value: '2209' },
      { label: 'пекарь', value: '5073' },
      { label: 'перси джексон', value: '6329' },
      { label: 'пилот', value: '5521' },
      { label: 'пират', value: '1579' },
      { label: 'писатель', value: '734' },
      { label: 'питомцы', value: '3122' },
      { label: 'пленница', value: '4897' },
      { label: 'повар', value: '658' },
      { label: 'повелитель демонов', value: '1325' },
      { label: 'подростки', value: '636' },
      { label: 'подруга', value: '5804' },
      { label: 'покемоны', value: '2840' },
      { label: 'полицейский', value: '1907' },
      { label: 'полубог', value: '7170' },
      { label: 'полулюди', value: '2273' },
      { label: 'правитель', value: '2261' },
      { label: 'президент', value: '4334' },
      { label: 'преступник', value: '4049' },
      { label: 'призрак', value: '511' },
      { label: 'принц', value: '362' },
      { label: 'принцесса', value: '2403' },
      { label: 'прислуга', value: '5185' },
      { label: 'пришельцы', value: '273' },
      { label: 'псайкеры', value: '3659' },
      { label: 'пэнси паркинсон', value: '7411' },
      { label: 'рабы', value: '1240' },
      { label: 'разработчик', value: '2333' },
      { label: 'ребенок', value: '2881' },
      { label: 'рейджер', value: '5147' },
      { label: 'рем', value: '6655' },
      { label: 'ремесленник', value: '1483' },
      { label: 'репликаторы', value: '3495' },
      { label: 'риас гремори', value: '6950' },
      { label: 'робот', value: '4011' },
      { label: 'рок ли', value: '7002' },
      { label: 'рокси', value: '7380' },
      { label: 'рон уизли', value: '4279' },
      { label: 'ророноа зоро', value: '1590' },
      { label: 'росомаха', value: '1035' },
      { label: 'рудеус', value: '7379' },
      { label: 'русалки', value: '3127' },
      { label: 'рыцари', value: '1902' },
      { label: 'рэо хатаке', value: '2823' },
      { label: 'сайян', value: '6802' },
      { label: 'сакура', value: '2515' },
      { label: 'самец', value: '1592' },
      { label: 'самураи', value: '576' },
      { label: 'санса старк', value: '3925' },
      { label: 'саске', value: '7237' },
      { label: 'священик', value: '61' },
      { label: 'северус снейп', value: '5783' },
      { label: 'семья', value: '728' },
      { label: 'сенджу', value: '6069' },
      { label: 'серийный убийца', value: '261' },
      { label: 'сестра', value: '2342' },
      { label: 'сильная главная героиня', value: '1994' },
      { label: 'сильный главный герой', value: '570' },
      { label: 'сильфиетта', value: '7381' },
      { label: 'симбиот', value: '2648' },
      { label: 'синигами', value: '7217' },
      { label: 'сириус блэк', value: '7655' },
      { label: 'сирота', value: '297' },
      { label: 'ситх', value: '1618' },
      { label: 'скайуокер', value: '6828' },
      { label: 'сквиб', value: '4101' },
      { label: 'скелет', value: '1315' },
      { label: 'скульптор', value: '1178' },
      { label: 'слабая главная героиня', value: '5805' },
      { label: 'слабый главный герой', value: '731' },
      { label: 'славяне', value: '2168' },
      { label: 'слизь', value: '1095' },
      { label: 'служанка', value: '3486' },
      { label: 'собаки', value: '6109' },
      { label: 'создатель', value: '1045' },
      { label: 'солдат', value: '1952' },
      { label: 'сома и эрина', value: '5737' },
      { label: 'соседи', value: '4075' },
      { label: 'сотрудник', value: '6339' },
      { label: 'спокойная главная героиня', value: '236' },
      { label: 'спокойный главный герой', value: '1656' },
      { label: 'сталкер', value: '1932' },
      { label: 'студент', value: '1464' },
      { label: 'студентка', value: '7518' },
      { label: 'суккубы', value: '2662' },
      { label: 'супергерои', value: '1481' },
      { label: 'суперзлодеи', value: '2125' },
      { label: 'супермен', value: '6997' },
      { label: 'существа', value: '6033' },
      { label: 'сын', value: '3297' },
      { label: 'сэм винчестер', value: '7461' },
      { label: 'тайцы', value: '6413' },
      { label: 'тейлор эберт', value: '3526' },
      { label: 'телохранитель', value: '723' },
      { label: 'темари', value: '4810' },
      { label: 'темные эльфы', value: '7198' },
      { label: 'тетя', value: '4194' },
      { label: 'тиран', value: '1174' },
      { label: 'титаны', value: '3308' },
      { label: 'тодороки шото', value: '5105' },
      { label: 'том реддл', value: '6652' },
      { label: 'тони старк', value: '1338' },
      { label: 'тор', value: '1800' },
      { label: 'тор и локи', value: '2645' },
      { label: 'трансформеры', value: '4616' },
      { label: 'трап', value: '6317' },
      { label: 'тревор филипс', value: '5427' },
      { label: 'тройняшки', value: '7169' },
      { label: 'троли', value: '4250' },
      { label: 'трудолюбивый главный герой', value: '248' },
      { label: 'тупой главный герой', value: '3710' },
      { label: 'тьма', value: '1919' },
      { label: 'убийцы', value: '1766' },
      { label: 'убийцы драконов', value: '1484' },
      { label: 'узумаки', value: '7579' },
      { label: 'умная главная героиня', value: '1381' },
      { label: 'умный главный герой', value: '2093' },
      { label: 'усопп', value: '6737' },
      { label: 'ученые', value: '1843' },
      { label: 'учитель', value: '845' },
      { label: 'учиха', value: '5348' },
      { label: 'фамильяры', value: '1471' },
      { label: 'фанаты', value: '7739' },
      { label: 'фармацевт', value: '1706' },
      { label: 'фашисты', value: '3118' },
      { label: 'феи', value: '7185' },
      { label: 'фелляция', value: '5880' },
      { label: 'феникс', value: '2413' },
      { label: 'фенрир', value: '2740' },
      { label: 'фехтовальщик', value: '4685' },
      { label: 'флер делакур', value: '5191' },
      { label: 'флэш', value: '4667' },
      { label: 'фокусник', value: '7602' },
      { label: 'фугаку', value: '6161' },
      { label: 'хакер', value: '475' },
      { label: 'халк', value: '1196' },
      { label: 'ханма юджиро', value: '4369' },
      { label: 'хан нуньен синг', value: '4817' },
      { label: 'харизматичный главный герой', value: '2350' },
      { label: 'хатаке какаши', value: '2820' },
      { label: 'хиддлстон', value: '5903' },
      { label: 'химавари', value: '2583' },
      { label: 'хината', value: '2513' },
      { label: 'хитрый главный герой', value: '2036' },
      { label: 'хоббит', value: '6698' },
      { label: 'холодная главная героиня', value: '6507' },
      { label: 'холодный главный герой', value: '2686' },
      { label: 'художница', value: '518' },
      { label: 'хулиганы', value: '854' },
      { label: 'цезарь', value: '1705' },
      { label: 'целители', value: '4523' },
      { label: 'цунаде', value: '6949' },
      { label: 'черви', value: '234' },
      { label: 'чернокнижник', value: '7005' },
      { label: 'честная главная героиня', value: '5855' },
      { label: 'честный главный герой', value: '129' },
      { label: 'шерлок холмс', value: '4818' },
      { label: 'шикамару нара', value: '5767' },
      { label: 'шинигами', value: '4661' },
      { label: 'шиноби', value: '1227' },
      { label: 'школьники', value: '218' },
      { label: 'школьницы', value: '5946' },
      { label: 'шлюха', value: '5822' },
      { label: 'шпионы', value: '4262' },
      { label: 'эванс', value: '5902' },
      { label: 'эйс', value: '6804' },
      { label: 'элементали', value: '2089' },
      { label: 'элизабет', value: '7377' },
      { label: 'эльза', value: '7245' },
      { label: 'эльфы', value: '1362' },
      { label: 'юки учиха', value: '7384' },
      { label: 'якудза', value: '4599' },
      { label: 'яманака', value: '7505' },
      { label: '12+', value: '3316' },
      { label: '16+', value: '83' },
      { label: '18+', value: '1749' },
      { label: '21+', value: '3191' },
      { label: 'алкоголь', value: '5508' },
      { label: 'анальный секс', value: '1942' },
      { label: 'бдсм', value: '444' },
      { label: 'без цензуры', value: '7525' },
      { label: 'бисексуалы', value: '5114' },
      { label: 'большая грудь', value: '4717' },
      { label: 'большой член', value: '5299' },
      { label: 'вагинальный секс', value: '4742' },
      { label: 'вирт', value: '6213' },
      { label: 'в первый раз', value: '6212' },
      { label: 'вуайеризм', value: '2498' },
      { label: 'гарем', value: '440' },
      { label: 'глотание спермы', value: '4491' },
      { label: 'групповой секс', value: '1314' },
      { label: 'доминирование', value: '2054' },
      { label: 'дрочка', value: '4565' },
      { label: 'женское доминирование', value: '4622' },
      { label: 'жесткий секс', value: '2238' },
      { label: 'жестокое обращение с детьми', value: '84' },
      { label: 'золотой дождь', value: '1828' },
      { label: 'зоофилия', value: '1165' },
      { label: 'извращения', value: '651' },
      { label: 'изнасилование', value: '1283' },
      { label: 'инквизитор', value: '143' },
      { label: 'инцест', value: '1934' },
      { label: 'каннибализм', value: '2249' },
      { label: 'кончил внутрь', value: '4589' },
      { label: 'копрофилия', value: '2568' },
      { label: 'кровь и расчлененка', value: '7752' },
      { label: 'ксенофилия', value: '2265' },
      { label: 'кунилингус', value: '4651' },
      { label: 'лишение девственности', value: '3512' },
      { label: 'мазохизм', value: '1961' },
      { label: 'мастурбация', value: '3078' },
      { label: 'межрасовый секс', value: '3489' },
      { label: 'милф', value: '1987' },
      { label: 'минет', value: '3289' },
      { label: 'много крови', value: '5318' },
      { label: 'наркотики', value: '1436' },
      { label: 'насилие и жестокость', value: '1440' },
      { label: 'неверность', value: '5735' },
      { label: 'некрофилия', value: '1285' },
      { label: 'ненормативная лексика', value: '160' },
      { label: 'нецензурная лексика', value: '4912' },
      { label: 'нудизм', value: '2233' },
      { label: 'омегаверс', value: '205' },
      { label: 'оральный секс', value: '605' },
      { label: 'оргия', value: '974' },
      { label: 'пайзури', value: '3560' },
      { label: 'пансексуалы', value: '4306' },
      { label: 'педофилия', value: '7052' },
      { label: 'первый раз', value: '1465' },
      { label: 'подчинение и унижение', value: '4500' },
      { label: 'порно', value: '4023' },
      { label: 'потеря девственности', value: '5879' },
      { label: 'принуждение', value: '1442' },
      { label: 'публичный секс', value: '6647' },
      { label: 'пытки', value: '1756' },
      { label: 'разврат', value: '1924' },
      { label: 'расчленение', value: '7125' },
      { label: 'самоубийство', value: '4312' },
      { label: 'свингеры', value: '514' },
      { label: 'связывание', value: '4506' },
      { label: 'секс', value: '2472' },
      { label: 'секса будет много', value: '7265' },
      { label: 'секс без проникновения', value: '151' },
      { label: 'секс игрушки', value: '1124' },
      { label: 'секс по согласию', value: '7307' },
      { label: 'секс рабыня', value: '7174' },
      { label: 'секс с близнецами', value: '7457' },
      { label: 'секс с монстрами', value: '6073' },
      { label: 'секс с учителем', value: '2570' },
      { label: 'сексуальные и психологические отклонения', value: '888' },
      { label: 'селфцест', value: '7498' },
      { label: 'сиськи', value: '16' },
      { label: 'сквирт', value: '4526' },
      { label: 'стриптиз', value: '6914' },
      { label: 'твинцест', value: '2450' },
      { label: 'тентакли', value: '3236' },
      { label: 'фетиш', value: '2398' },
      { label: 'фистинг', value: '4206' },
      { label: 'хентай', value: '1682' },
      { label: 'эксгибиционизм', value: '1643' },
      { label: 'элементы бдсм', value: '1323' },
      { label: 'эротика', value: '2053' },
      { label: 'сильные противники', value: '7801' },
    ],
    inputType: FilterInputs.Checkbox,
  },
  {
    key: 'adult',
    label: 'Возрастные ограничения',
    values: [
      { label: 'Все', value: '0' },
      { label: 'Убрать 18+', value: '1' },
      { label: 'Только 18+', value: '2' },
    ],
    inputType: FilterInputs.Picker,
  },
];

const RulateLibScraper = {
  popularNovels,
  parseNovelAndChapters,
  parseChapter,
  searchNovels,
  filters,
};

export default RulateLibScraper;
